# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bernard/book-2022.1/new_book_ip/multicore_multicycle_ip/z1_multicore_multicycle_4c_ip.srcs/sources_1/bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_20/design_1_4c_multicycle_pipeline_0_20.xci
# IP: The module: 'design_1_4c_multicycle_pipeline_0_20' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bernard/book-2022.1/new_book_ip/multicore_multicycle_ip/z1_multicore_multicycle_4c_ip.gen/sources_1/bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_20/constraints/multicycle_pipeline_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_4c_multicycle_pipeline_0_20'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bernard/book-2022.1/new_book_ip/multicore_multicycle_ip/z1_multicore_multicycle_4c_ip.srcs/sources_1/bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_20/design_1_4c_multicycle_pipeline_0_20.xci
# IP: The module: 'design_1_4c_multicycle_pipeline_0_20' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bernard/book-2022.1/new_book_ip/multicore_multicycle_ip/z1_multicore_multicycle_4c_ip.gen/sources_1/bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_20/constraints/multicycle_pipeline_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_4c_multicycle_pipeline_0_20'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
