-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity multihart_ip is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 18;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    ip_data_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    ip_data_ram_EN_A : OUT STD_LOGIC;
    ip_data_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    ip_data_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    ip_data_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    ip_data_ram_Clk_A : OUT STD_LOGIC;
    ip_data_ram_Rst_A : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of multihart_ip is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "multihart_ip_multihart_ip,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.256300,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=68,HLS_SYN_DSP=0,HLS_SYN_FF=8662,HLS_SYN_LUT=13177,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv19_20000 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal ip_num : STD_LOGIC_VECTOR (31 downto 0);
    signal running_hart_set : STD_LOGIC_VECTOR (31 downto 0);
    signal start_pc_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ip_code_ram_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_ram : STD_LOGIC_VECTOR (63 downto 0);
    signal nb_instruction_ap_vld : STD_LOGIC;
    signal nb_cycle_ap_vld : STD_LOGIC;
    signal f_state_fetch_pc_fu_199_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal f_state_fetch_pc_reg_296 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal data_ram_read_reg_306 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal h_running_fu_203_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_running_reg_311 : STD_LOGIC_VECTOR (0 downto 0);
    signal has_exited_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal has_exited_reg_316 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_running_2_fu_213_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_running_2_reg_321 : STD_LOGIC_VECTOR (0 downto 0);
    signal has_exited_6_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal has_exited_6_reg_326 : STD_LOGIC_VECTOR (0 downto 0);
    signal f_state_fetch_pc_12_fu_227_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal f_state_fetch_pc_12_reg_331 : STD_LOGIC_VECTOR (14 downto 0);
    signal reg_file_131_fu_231_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_file_131_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_file_fu_247_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_file_reg_343 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_cast_reg_348 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_i_i_i_fu_263_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_i_i_i_reg_353 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_idle : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_ready : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_ce0 : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_EN_A : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbi_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbi_1_out_ap_vld : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbc_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbc_1_out_ap_vld : STD_LOGIC;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARVALID : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RREADY : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal start_pc_ce0_local : STD_LOGIC;
    signal start_pc_address0_local : STD_LOGIC_VECTOR (0 downto 0);
    signal add_i_i24_i_fu_235_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_i_i24_i_cast_fu_243_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component multihart_ip_multihart_ip_Pipeline_VITIS_LOOP_197_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        has_exited_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        has_exited : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_19 : IN STD_LOGIC_VECTOR (14 downto 0);
        empty_20 : IN STD_LOGIC_VECTOR (14 downto 0);
        empty_21 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_22 : IN STD_LOGIC_VECTOR (0 downto 0);
        reg_file_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln120 : IN STD_LOGIC_VECTOR (18 downto 0);
        p_cast_cast : IN STD_LOGIC_VECTOR (61 downto 0);
        ip_code_ram_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        ip_code_ram_ce0 : OUT STD_LOGIC;
        ip_code_ram_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        shl_i_i_i : IN STD_LOGIC_VECTOR (1 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        ip_data_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        ip_data_ram_EN_A : OUT STD_LOGIC;
        ip_data_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        ip_data_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        ip_data_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        data_ram : IN STD_LOGIC_VECTOR (63 downto 0);
        nbi_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        nbi_1_out_ap_vld : OUT STD_LOGIC;
        nbc_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        nbc_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component multihart_ip_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ip_num : OUT STD_LOGIC_VECTOR (31 downto 0);
        running_hart_set : OUT STD_LOGIC_VECTOR (31 downto 0);
        start_pc_address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        start_pc_ce0 : IN STD_LOGIC;
        start_pc_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_ram : OUT STD_LOGIC_VECTOR (63 downto 0);
        nb_instruction : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_instruction_ap_vld : IN STD_LOGIC;
        nb_cycle : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_cycle_ap_vld : IN STD_LOGIC;
        ip_code_ram_address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ip_code_ram_ce0 : IN STD_LOGIC;
        ip_code_ram_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component multihart_ip_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175 : component multihart_ip_multihart_ip_Pipeline_VITIS_LOOP_197_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start,
        ap_done => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done,
        ap_idle => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_idle,
        ap_ready => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_ready,
        m_axi_gmem_AWVALID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        has_exited_1 => has_exited_6_reg_326,
        has_exited => has_exited_reg_316,
        empty_19 => f_state_fetch_pc_12_reg_331,
        empty_20 => f_state_fetch_pc_reg_296,
        empty_21 => h_running_2_reg_321,
        empty_22 => h_running_reg_311,
        reg_file_1 => reg_file_131_reg_336,
        zext_ln120 => reg_file_reg_343,
        p_cast_cast => p_cast_reg_348,
        ip_code_ram_address0 => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_address0,
        ip_code_ram_ce0 => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_ce0,
        ip_code_ram_q0 => ip_code_ram_q0,
        shl_i_i_i => shl_i_i_i_reg_353,
        empty => reg_file_131_reg_336,
        ip_data_ram_Addr_A => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Addr_A,
        ip_data_ram_EN_A => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_EN_A,
        ip_data_ram_WEN_A => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_WEN_A,
        ip_data_ram_Din_A => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Din_A,
        ip_data_ram_Dout_A => ip_data_ram_Dout_A,
        data_ram => data_ram_read_reg_306,
        nbi_1_out => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbi_1_out,
        nbi_1_out_ap_vld => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbi_1_out_ap_vld,
        nbc_1_out => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbc_1_out,
        nbc_1_out_ap_vld => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbc_1_out_ap_vld);

    control_s_axi_U : component multihart_ip_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ip_num => ip_num,
        running_hart_set => running_hart_set,
        start_pc_address0 => start_pc_address0_local,
        start_pc_ce0 => start_pc_ce0_local,
        start_pc_q0 => start_pc_q0,
        data_ram => data_ram,
        nb_instruction => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbi_1_out,
        nb_instruction_ap_vld => nb_instruction_ap_vld,
        nb_cycle => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_nbc_1_out,
        nb_cycle_ap_vld => nb_cycle_ap_vld,
        ip_code_ram_address0 => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_address0,
        ip_code_ram_ce0 => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_code_ram_ce0,
        ip_code_ram_q0 => ip_code_ram_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component multihart_ip_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_ARVALID,
        I_CH0_ARREADY => gmem_ARREADY,
        I_CH0_ARADDR => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARADDR,
        I_CH0_ARLEN => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARLEN,
        I_CH0_RVALID => gmem_RVALID,
        I_CH0_RREADY => gmem_RREADY,
        I_CH0_RDATA => gmem_RDATA,
        I_CH0_RFIFONUM => gmem_RFIFONUM,
        I_CH0_AWVALID => gmem_AWVALID,
        I_CH0_AWREADY => gmem_AWREADY,
        I_CH0_AWADDR => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWADDR,
        I_CH0_AWLEN => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWLEN,
        I_CH0_WVALID => gmem_WVALID,
        I_CH0_WREADY => gmem_WREADY,
        I_CH0_WDATA => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WDATA,
        I_CH0_WSTRB => grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WSTRB,
        I_CH0_BVALID => gmem_BVALID,
        I_CH0_BREADY => gmem_BREADY);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_ready = ap_const_logic_1)) then 
                    grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                data_ram_read_reg_306 <= data_ram;
                f_state_fetch_pc_12_reg_331 <= f_state_fetch_pc_12_fu_227_p1;
                h_running_2_reg_321 <= running_hart_set(1 downto 1);
                h_running_reg_311 <= h_running_fu_203_p1;
                has_exited_6_reg_326 <= has_exited_6_fu_221_p2;
                has_exited_reg_316 <= has_exited_fu_207_p2;
                p_cast_reg_348 <= data_ram(63 downto 2);
                reg_file_131_reg_336 <= reg_file_131_fu_231_p1;
                    reg_file_reg_343(18 downto 17) <= reg_file_fu_247_p2(18 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                f_state_fetch_pc_reg_296 <= f_state_fetch_pc_fu_199_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    shl_i_i_i_reg_353(1) <= shl_i_i_i_fu_263_p3(1);
            end if;
        end if;
    end process;
    reg_file_reg_343(16 downto 0) <= "00000000000000000";
    shl_i_i_i_reg_353(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_i_i24_i_cast_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_i_i24_i_fu_235_p3),19));
    add_i_i24_i_fu_235_p3 <= (reg_file_131_fu_231_p1 & ap_const_lv17_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done)
    begin
        if ((grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    f_state_fetch_pc_12_fu_227_p1 <= start_pc_q0(15 - 1 downto 0);
    f_state_fetch_pc_fu_199_p1 <= start_pc_q0(15 - 1 downto 0);

    gmem_ARVALID_assign_proc : process(ap_CS_fsm_state4, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_ARVALID <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_ARVALID;
        else 
            gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_AWVALID_assign_proc : process(ap_CS_fsm_state4, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_AWVALID <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_AWVALID;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(ap_CS_fsm_state4, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_BREADY, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_BREADY <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_BREADY;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_RREADY_assign_proc : process(ap_CS_fsm_state4, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_RREADY, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_RREADY <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_RREADY;
        else 
            gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(ap_CS_fsm_state4, grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_WVALID <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_m_axi_gmem_WVALID;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ap_start_reg;
    h_running_2_fu_213_p3 <= running_hart_set(1 downto 1);
    h_running_fu_203_p1 <= running_hart_set(1 - 1 downto 0);
    has_exited_6_fu_221_p2 <= (h_running_2_fu_213_p3 xor ap_const_lv1_1);
    has_exited_fu_207_p2 <= (h_running_fu_203_p1 xor ap_const_lv1_1);
    ip_data_ram_Addr_A <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Addr_A;
    ip_data_ram_Clk_A <= ap_clk;
    ip_data_ram_Din_A <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_Din_A;
    ip_data_ram_EN_A <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_EN_A;

    ip_data_ram_Rst_A_assign_proc : process(ap_rst_n)
    begin
                ip_data_ram_Rst_A <= not(ap_rst_n);
    end process;

    ip_data_ram_WEN_A <= grp_multihart_ip_Pipeline_VITIS_LOOP_197_1_fu_175_ip_data_ram_WEN_A;

    nb_cycle_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            nb_cycle_ap_vld <= ap_const_logic_1;
        else 
            nb_cycle_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    nb_instruction_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            nb_instruction_ap_vld <= ap_const_logic_1;
        else 
            nb_instruction_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_131_fu_231_p1 <= ip_num(1 - 1 downto 0);
    reg_file_fu_247_p2 <= std_logic_vector(unsigned(add_i_i24_i_cast_fu_243_p1) + unsigned(ap_const_lv19_20000));
    shl_i_i_i_fu_263_p3 <= (reg_file_131_reg_336 & ap_const_lv1_0);

    start_pc_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            start_pc_address0_local <= ap_const_lv64_1(1 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            start_pc_address0_local <= ap_const_lv64_0(1 - 1 downto 0);
        else 
            start_pc_address0_local <= "X";
        end if; 
    end process;


    start_pc_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            start_pc_ce0_local <= ap_const_logic_1;
        else 
            start_pc_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

end behav;
