# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_4c/design_1_4c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c || ORIG_REF_NAME==design_1_4c} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_processing_system7_0_0/design_1_4c_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_processing_system7_0_0 || ORIG_REF_NAME==design_1_4c_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_axi_bram_ctrl_0_0/design_1_4c_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_4c_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_axi_bram_ctrl_0_1/design_1_4c_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_4c_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_axi_bram_ctrl_0_2/design_1_4c_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_axi_bram_ctrl_0_2 || ORIG_REF_NAME==design_1_4c_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_axi_bram_ctrl_0_3/design_1_4c_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_axi_bram_ctrl_0_3 || ORIG_REF_NAME==design_1_4c_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_blk_mem_gen_0_0/design_1_4c_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_4c_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_blk_mem_gen_0_1/design_1_4c_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_4c_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_blk_mem_gen_0_2/design_1_4c_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_4c_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_blk_mem_gen_0_3/design_1_4c_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_blk_mem_gen_0_3 || ORIG_REF_NAME==design_1_4c_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_rst_ps7_0_100M_0/design_1_4c_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_4c_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_xbar_1/design_1_4c_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_xbar_1 || ORIG_REF_NAME==design_1_4c_xbar_1} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_axi_interconnect_0_1/design_1_4c_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_4c_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_auto_pc_0/design_1_4c_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_auto_pc_0 || ORIG_REF_NAME==design_1_4c_auto_pc_0} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_auto_pc_1/design_1_4c_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_auto_pc_1 || ORIG_REF_NAME==design_1_4c_auto_pc_1} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_auto_pc_2/design_1_4c_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_auto_pc_2 || ORIG_REF_NAME==design_1_4c_auto_pc_2} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_auto_pc_3/design_1_4c_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_auto_pc_3 || ORIG_REF_NAME==design_1_4c_auto_pc_3} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_auto_pc_4/design_1_4c_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_auto_pc_4 || ORIG_REF_NAME==design_1_4c_auto_pc_4} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_24/design_1_4c_multicycle_pipeline_0_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_multicycle_pipeline_0_24 || ORIG_REF_NAME==design_1_4c_multicycle_pipeline_0_24} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_25/design_1_4c_multicycle_pipeline_0_25.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_multicycle_pipeline_0_25 || ORIG_REF_NAME==design_1_4c_multicycle_pipeline_0_25} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_26/design_1_4c_multicycle_pipeline_0_26.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_multicycle_pipeline_0_26 || ORIG_REF_NAME==design_1_4c_multicycle_pipeline_0_26} -quiet] -quiet

# IP: bd/design_1_4c/ip/design_1_4c_multicycle_pipeline_0_27/design_1_4c_multicycle_pipeline_0_27.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4c_multicycle_pipeline_0_27 || ORIG_REF_NAME==design_1_4c_multicycle_pipeline_0_27} -quiet] -quiet

# XDC: /home/goossens/book-2022.1/new_book_ip/multicore_multicycle_ip/z1_multicore_multicycle_4c_ip.gen/sources_1/bd/design_1_4c/design_1_4c_ooc.xdc
