// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fetching_ip_running_cond_update (
        ap_ready,
        instruction,
        ap_return
);


output   ap_ready;
input  [31:0] instruction;
output  [0:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = ((instruction != 32'd32871) ? 1'b1 : 1'b0);

endmodule //fetching_ip_running_cond_update
