-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rv32i_npp_ip is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    code_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    code_ram_EN_A : OUT STD_LOGIC;
    code_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    code_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    code_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    code_ram_Clk_A : OUT STD_LOGIC;
    code_ram_Rst_A : OUT STD_LOGIC;
    data_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_ram_EN_A : OUT STD_LOGIC;
    data_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    data_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    data_ram_Clk_A : OUT STD_LOGIC;
    data_ram_Rst_A : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of rv32i_npp_ip is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "rv32i_npp_ip_rv32i_npp_ip,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.357600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1522,HLS_SYN_LUT=3218,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal start_pc : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_instruction_ap_vld : STD_LOGIC;
    signal pc_V_fu_397_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal pc_V_reg_700 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_idle : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_ready : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_31_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_31_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_30_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_30_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_29_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_29_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_28_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_28_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_27_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_27_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_26_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_26_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_25_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_25_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_24_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_24_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_23_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_23_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_22_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_22_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_21_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_21_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_20_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_20_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_19_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_19_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_18_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_18_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_17_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_17_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_16_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_16_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_15_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_15_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_14_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_13_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_13_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_12_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_12_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_11_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_10_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_9_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_8_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_7_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_6_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_5_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_4_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_3_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_2_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_1_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_idle : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_ready : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_EN_A : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_EN_A : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_nbi_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_nbi_out_ap_vld : STD_LOGIC;
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rv32i_npp_ip_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_file_31_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_31_out_ap_vld : OUT STD_LOGIC;
        reg_file_30_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_30_out_ap_vld : OUT STD_LOGIC;
        reg_file_29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_29_out_ap_vld : OUT STD_LOGIC;
        reg_file_28_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_28_out_ap_vld : OUT STD_LOGIC;
        reg_file_27_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_27_out_ap_vld : OUT STD_LOGIC;
        reg_file_26_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_26_out_ap_vld : OUT STD_LOGIC;
        reg_file_25_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_25_out_ap_vld : OUT STD_LOGIC;
        reg_file_24_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_24_out_ap_vld : OUT STD_LOGIC;
        reg_file_23_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_23_out_ap_vld : OUT STD_LOGIC;
        reg_file_22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_22_out_ap_vld : OUT STD_LOGIC;
        reg_file_21_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_21_out_ap_vld : OUT STD_LOGIC;
        reg_file_20_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_20_out_ap_vld : OUT STD_LOGIC;
        reg_file_19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_19_out_ap_vld : OUT STD_LOGIC;
        reg_file_18_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_18_out_ap_vld : OUT STD_LOGIC;
        reg_file_17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_17_out_ap_vld : OUT STD_LOGIC;
        reg_file_16_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_16_out_ap_vld : OUT STD_LOGIC;
        reg_file_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_15_out_ap_vld : OUT STD_LOGIC;
        reg_file_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_14_out_ap_vld : OUT STD_LOGIC;
        reg_file_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_13_out_ap_vld : OUT STD_LOGIC;
        reg_file_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_12_out_ap_vld : OUT STD_LOGIC;
        reg_file_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_11_out_ap_vld : OUT STD_LOGIC;
        reg_file_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_10_out_ap_vld : OUT STD_LOGIC;
        reg_file_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_9_out_ap_vld : OUT STD_LOGIC;
        reg_file_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_8_out_ap_vld : OUT STD_LOGIC;
        reg_file_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_7_out_ap_vld : OUT STD_LOGIC;
        reg_file_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_6_out_ap_vld : OUT STD_LOGIC;
        reg_file_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_5_out_ap_vld : OUT STD_LOGIC;
        reg_file_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_4_out_ap_vld : OUT STD_LOGIC;
        reg_file_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_3_out_ap_vld : OUT STD_LOGIC;
        reg_file_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_2_out_ap_vld : OUT STD_LOGIC;
        reg_file_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_1_out_ap_vld : OUT STD_LOGIC;
        reg_file_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_out_ap_vld : OUT STD_LOGIC );
    end component;


    component rv32i_npp_ip_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_file_26_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_27_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_28_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_29_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_30_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        pc_V : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_25_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_24_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_23_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_22_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_21_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_20_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_19_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_18_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_17_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_16_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_31_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        code_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        code_ram_EN_A : OUT STD_LOGIC;
        code_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        code_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        code_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        data_ram_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_ram_EN_A : OUT STD_LOGIC;
        data_ram_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        data_ram_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_ram_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        nbi_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        nbi_out_ap_vld : OUT STD_LOGIC );
    end component;


    component rv32i_npp_ip_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        start_pc : OUT STD_LOGIC_VECTOR (31 downto 0);
        nb_instruction : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_instruction_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191 : component rv32i_npp_ip_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start,
        ap_done => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done,
        ap_idle => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_idle,
        ap_ready => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_ready,
        reg_file_31_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_31_out,
        reg_file_31_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_31_out_ap_vld,
        reg_file_30_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_30_out,
        reg_file_30_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_30_out_ap_vld,
        reg_file_29_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_29_out,
        reg_file_29_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_29_out_ap_vld,
        reg_file_28_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_28_out,
        reg_file_28_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_28_out_ap_vld,
        reg_file_27_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_27_out,
        reg_file_27_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_27_out_ap_vld,
        reg_file_26_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_26_out,
        reg_file_26_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_26_out_ap_vld,
        reg_file_25_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_25_out,
        reg_file_25_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_25_out_ap_vld,
        reg_file_24_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_24_out,
        reg_file_24_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_24_out_ap_vld,
        reg_file_23_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_23_out,
        reg_file_23_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_23_out_ap_vld,
        reg_file_22_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_22_out,
        reg_file_22_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_22_out_ap_vld,
        reg_file_21_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_21_out,
        reg_file_21_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_21_out_ap_vld,
        reg_file_20_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_20_out,
        reg_file_20_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_20_out_ap_vld,
        reg_file_19_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_19_out,
        reg_file_19_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_19_out_ap_vld,
        reg_file_18_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_18_out,
        reg_file_18_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_18_out_ap_vld,
        reg_file_17_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_17_out,
        reg_file_17_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_17_out_ap_vld,
        reg_file_16_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_16_out,
        reg_file_16_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_16_out_ap_vld,
        reg_file_15_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_15_out,
        reg_file_15_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_15_out_ap_vld,
        reg_file_14_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_14_out,
        reg_file_14_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_14_out_ap_vld,
        reg_file_13_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_13_out,
        reg_file_13_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_13_out_ap_vld,
        reg_file_12_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_12_out,
        reg_file_12_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_12_out_ap_vld,
        reg_file_11_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_11_out,
        reg_file_11_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_11_out_ap_vld,
        reg_file_10_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_10_out,
        reg_file_10_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_10_out_ap_vld,
        reg_file_9_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_9_out,
        reg_file_9_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_9_out_ap_vld,
        reg_file_8_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_8_out,
        reg_file_8_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_8_out_ap_vld,
        reg_file_7_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_7_out,
        reg_file_7_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_7_out_ap_vld,
        reg_file_6_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_6_out,
        reg_file_6_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_6_out_ap_vld,
        reg_file_5_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_5_out,
        reg_file_5_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_5_out_ap_vld,
        reg_file_4_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_4_out,
        reg_file_4_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_4_out_ap_vld,
        reg_file_3_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_3_out,
        reg_file_3_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_3_out_ap_vld,
        reg_file_2_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_2_out,
        reg_file_2_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_2_out_ap_vld,
        reg_file_1_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_1_out,
        reg_file_1_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_1_out_ap_vld,
        reg_file_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_out,
        reg_file_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_out_ap_vld);

    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227 : component rv32i_npp_ip_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start,
        ap_done => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done,
        ap_idle => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_idle,
        ap_ready => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_ready,
        reg_file_26_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_26_out,
        reg_file_27_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_27_out,
        reg_file_28_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_28_out,
        reg_file_29_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_29_out,
        reg_file_30_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_30_out,
        pc_V => pc_V_reg_700,
        reg_file_25_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_25_out,
        reg_file_24_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_24_out,
        reg_file_23_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_23_out,
        reg_file_22_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_22_out,
        reg_file_21_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_21_out,
        reg_file_20_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_20_out,
        reg_file_19_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_19_out,
        reg_file_18_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_18_out,
        reg_file_17_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_17_out,
        reg_file_16_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_16_out,
        reg_file_15_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_15_out,
        reg_file_14_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_14_out,
        reg_file_13_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_13_out,
        reg_file_12_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_12_out,
        reg_file_11_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_11_out,
        reg_file_10_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_10_out,
        reg_file_9_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_9_out,
        reg_file_8_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_8_out,
        reg_file_7_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_7_out,
        reg_file_6_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_6_out,
        reg_file_5_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_5_out,
        reg_file_4_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_4_out,
        reg_file_3_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_3_out,
        reg_file_2_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_2_out,
        reg_file_1_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_1_out,
        reg_file_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_out,
        reg_file_31_reload => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_reg_file_31_out,
        code_ram_Addr_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_Addr_A,
        code_ram_EN_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_EN_A,
        code_ram_WEN_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_WEN_A,
        code_ram_Din_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_Din_A,
        code_ram_Dout_A => code_ram_Dout_A,
        data_ram_Addr_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Addr_A,
        data_ram_EN_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_EN_A,
        data_ram_WEN_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_WEN_A,
        data_ram_Din_A => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Din_A,
        data_ram_Dout_A => data_ram_Dout_A,
        nbi_out => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_nbi_out,
        nbi_out_ap_vld => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_nbi_out_ap_vld);

    control_s_axi_U : component rv32i_npp_ip_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        start_pc => start_pc,
        nb_instruction => grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_nbi_out,
        nb_instruction_ap_vld => nb_instruction_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_ready = ap_const_logic_1)) then 
                    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_ready = ap_const_logic_1)) then 
                    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                pc_V_reg_700 <= pc_V_fu_397_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done, grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done)
    begin
        if ((grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done)
    begin
        if ((grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    code_ram_Addr_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_Addr_A;
    code_ram_Clk_A <= ap_clk;
    code_ram_Din_A <= ap_const_lv32_0;
    code_ram_EN_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_code_ram_EN_A;
    code_ram_Rst_A <= ap_rst_n_inv;
    code_ram_WEN_A <= ap_const_lv4_0;
    data_ram_Addr_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Addr_A;
    data_ram_Clk_A <= ap_clk;
    data_ram_Din_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_Din_A;
    data_ram_EN_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_EN_A;
    data_ram_Rst_A <= ap_rst_n_inv;
    data_ram_WEN_A <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_data_ram_WEN_A;
    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_42_1_fu_191_ap_start_reg;
    grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start <= grp_rv32i_npp_ip_Pipeline_VITIS_LOOP_45_2_fu_227_ap_start_reg;

    nb_instruction_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            nb_instruction_ap_vld <= ap_const_logic_1;
        else 
            nb_instruction_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pc_V_fu_397_p1 <= start_pc(16 - 1 downto 0);
end behav;
