# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_1/design_1_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_multicycle_pipeline_0_18/design_1_multicycle_pipeline_0_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_multicycle_pipeline_0_18 || ORIG_REF_NAME==design_1_multicycle_pipeline_0_18} -quiet] -quiet

# XDC: /home/goossens/book-2022.1/new_book_ip/multicycle_pipeline_ip/z1_multicycle_pipeline_ip.gen/sources_1/bd/design_1/design_1_ooc.xdc
