// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fde_ip_decode (
        ap_ready,
        instruction,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [31:0] instruction;
output  [4:0] ap_return_0;
output  [4:0] ap_return_1;
output  [2:0] ap_return_2;
output  [4:0] ap_return_3;
output  [4:0] ap_return_4;
output  [6:0] ap_return_5;
output  [2:0] ap_return_6;
output  [19:0] ap_return_7;

reg   [2:0] ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50;
wire   [1:0] opch_V_fu_256_p4;
wire   [2:0] opcl_V_fu_266_p4;
wire   [19:0] ret_V_1_fu_396_p5;
reg   [19:0] ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12;
wire  signed [19:0] sext_ln75_2_fu_332_p1;
wire  signed [19:0] sext_ln75_1_fu_345_p1;
wire  signed [19:0] sext_ln75_fu_360_p1;
wire   [0:0] d_imm_inst_31_V_fu_276_p3;
wire   [0:0] d_imm_inst_7_V_fu_302_p3;
wire   [5:0] tmp_4_fu_310_p4;
wire   [3:0] d_imm_inst_11_8_V_fu_292_p4;
wire   [11:0] ret_V_4_fu_320_p5;
wire   [6:0] d_i_func7_V_write_assign_fu_246_p4;
wire   [4:0] d_i_rd_V_write_assign_fu_206_p4;
wire   [11:0] ret_V_3_fu_337_p3;
wire   [11:0] ret_V_fu_350_p4;
wire   [7:0] tmp_fu_376_p4;
wire   [0:0] d_imm_inst_20_V_fu_284_p3;
wire   [9:0] tmp_1_fu_386_p4;
wire    ap_ce_reg;

always @ (*) begin
    if (((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd0) | ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd1) | (ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd7)))) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = 20'd0;
    end else if ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd2)) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = sext_ln75_fu_360_p1;
    end else if ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd3)) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = sext_ln75_1_fu_345_p1;
    end else if ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd4)) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = sext_ln75_2_fu_332_p1;
    end else if ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd5)) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = {{instruction[31:12]}};
    end else if ((ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 == 3'd6)) begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = ret_V_1_fu_396_p5;
    end else begin
        ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12 = 'bx;
    end
end

always @ (*) begin
    if (((opcl_V_fu_266_p4 == 3'd0) & (opch_V_fu_256_p4 == 2'd3))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd4;
    end else if (((opcl_V_fu_266_p4 == 3'd0) & (opch_V_fu_256_p4 == 2'd1))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd3;
    end else if ((((opcl_V_fu_266_p4 == 3'd0) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd4) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd1) & (opch_V_fu_256_p4 == 2'd3)))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd2;
    end else if (((opcl_V_fu_266_p4 == 3'd3) & (opch_V_fu_256_p4 == 2'd3))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd6;
    end else if (((opcl_V_fu_266_p4 == 3'd4) & (opch_V_fu_256_p4 == 2'd1))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd1;
    end else if ((((opcl_V_fu_266_p4 == 3'd5) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd5) & (opch_V_fu_256_p4 == 2'd0)))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd5;
    end else if (((opch_V_fu_256_p4 == 2'd2) | ((opcl_V_fu_266_p4 == 3'd4) & (opch_V_fu_256_p4 == 2'd3)) | ((opcl_V_fu_266_p4 == 3'd1) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd1) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd2) & (opch_V_fu_256_p4 == 2'd3)) | ((opcl_V_fu_266_p4 == 3'd2) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd2) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd3) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd3) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd5) & (opch_V_fu_256_p4 == 2'd3)) | ((opcl_V_fu_266_p4 == 3'd6) & (opch_V_fu_256_p4 == 2'd3)) | ((opcl_V_fu_266_p4 == 3'd6) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd6) & (opch_V_fu_256_p4 == 2'd0)) | ((opcl_V_fu_266_p4 == 3'd7) & (opch_V_fu_256_p4 == 2'd3)) | ((opcl_V_fu_266_p4 == 3'd7) & (opch_V_fu_256_p4 == 2'd1)) | ((opcl_V_fu_266_p4 == 3'd7) & (opch_V_fu_256_p4 == 2'd0)))) begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 3'd7;
    end else begin
        ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ap_return_0 = {{instruction[6:2]}};

assign ap_return_1 = {{instruction[11:7]}};

assign ap_return_2 = {{instruction[14:12]}};

assign ap_return_3 = {{instruction[19:15]}};

assign ap_return_4 = {{instruction[24:20]}};

assign ap_return_5 = {{instruction[31:25]}};

assign ap_return_6 = ap_phi_mux_d_i_type_V_write_assign_phi_fu_101_p50;

assign ap_return_7 = ap_phi_mux_d_i_imm_V_write_assign_phi_fu_181_p12;

assign d_i_func7_V_write_assign_fu_246_p4 = {{instruction[31:25]}};

assign d_i_rd_V_write_assign_fu_206_p4 = {{instruction[11:7]}};

assign d_imm_inst_11_8_V_fu_292_p4 = {{instruction[11:8]}};

assign d_imm_inst_20_V_fu_284_p3 = instruction[32'd20];

assign d_imm_inst_31_V_fu_276_p3 = instruction[32'd31];

assign d_imm_inst_7_V_fu_302_p3 = instruction[32'd7];

assign opch_V_fu_256_p4 = {{instruction[6:5]}};

assign opcl_V_fu_266_p4 = {{instruction[4:2]}};

assign ret_V_1_fu_396_p5 = {{{{d_imm_inst_31_V_fu_276_p3}, {tmp_fu_376_p4}}, {d_imm_inst_20_V_fu_284_p3}}, {tmp_1_fu_386_p4}};

assign ret_V_3_fu_337_p3 = {{d_i_func7_V_write_assign_fu_246_p4}, {d_i_rd_V_write_assign_fu_206_p4}};

assign ret_V_4_fu_320_p5 = {{{{d_imm_inst_31_V_fu_276_p3}, {d_imm_inst_7_V_fu_302_p3}}, {tmp_4_fu_310_p4}}, {d_imm_inst_11_8_V_fu_292_p4}};

assign ret_V_fu_350_p4 = {{instruction[31:20]}};

assign sext_ln75_1_fu_345_p1 = $signed(ret_V_3_fu_337_p3);

assign sext_ln75_2_fu_332_p1 = $signed(ret_V_4_fu_320_p5);

assign sext_ln75_fu_360_p1 = $signed(ret_V_fu_350_p4);

assign tmp_1_fu_386_p4 = {{instruction[30:21]}};

assign tmp_4_fu_310_p4 = {{instruction[30:25]}};

assign tmp_fu_376_p4 = {{instruction[19:12]}};

endmodule //fde_ip_decode
