// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rv32i_pp_ip_rv32i_pp_ip,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.031000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=128,HLS_SYN_DSP=0,HLS_SYN_FF=2296,HLS_SYN_LUT=3945,HLS_VERSION=2024_1}" *)

module rv32i_pp_ip (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 19;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_ready;
wire    ap_CS_fsm_state3;
wire   [0:0] or_ln21_3_fu_2904_p2;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] start_pc;
wire   [14:0] code_ram_address0;
wire   [31:0] code_ram_q0;
wire   [31:0] data_ram_q0;
wire   [31:0] nb_instruction;
reg    nb_instruction_ap_vld;
reg    nb_cycle_ap_vld;
reg   [0:0] e_to_e_1_reg_600;
reg   [0:0] e_to_m_cancel_1_reg_611;
reg   [0:0] m_to_w_cancel_1_reg_623;
reg   [0:0] f7_6_reg_635;
reg   [0:0] result_25_reg_646;
reg   [0:0] w_from_m_has_no_dest_load_reg_3426;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] m_from_e_d_i_is_store_load_reg_3430;
reg   [4:0] m_to_w_rd_3_reg_3434;
reg   [31:0] e_to_m_result_2_reg_3438;
reg   [4:0] f_to_e_d_i_rs2_reg_3443;
reg   [31:0] m_to_w_result_2_reg_3448;
reg   [4:0] e_to_m_d_i_rd_3_reg_3485;
wire   [2:0] f_to_e_d_i_func3_load_fu_1139_p1;
reg   [2:0] f_to_e_d_i_func3_reg_3490;
wire   [14:0] pc_fu_1142_p3;
reg   [14:0] pc_reg_3495;
wire   [0:0] xor_ln32_fu_1478_p2;
reg   [0:0] xor_ln32_reg_3506;
wire   [31:0] rv1_fu_1576_p3;
reg   [31:0] rv1_reg_3511;
wire   [16:0] trunc_ln59_fu_1584_p1;
reg   [16:0] trunc_ln59_reg_3530;
wire   [31:0] rv2_fu_1596_p3;
reg   [31:0] rv2_reg_3535;
reg   [2:0] msize_load_reg_3545;
wire   [1:0] a01_fu_1607_p1;
reg   [1:0] a01_reg_3554;
wire   [0:0] a1_fu_1611_p3;
reg   [0:0] a1_reg_3561;
reg   [14:0] data_ram_addr_reg_3566;
reg   [31:0] e_to_m_rv2_1_load_reg_3571;
wire   [1:0] msize_1_fu_1637_p1;
reg   [1:0] msize_1_reg_3576;
wire   [3:0] shl_ln79_fu_1665_p2;
reg   [3:0] shl_ln79_reg_3580;
wire   [31:0] shl_ln79_2_fu_1683_p2;
reg   [31:0] shl_ln79_2_reg_3585;
wire   [3:0] shl_ln76_fu_1697_p2;
reg   [3:0] shl_ln76_reg_3590;
wire   [31:0] shl_ln76_2_fu_1715_p2;
reg   [31:0] shl_ln76_2_reg_3595;
reg   [0:0] is_ret_load_reg_3600;
wire    ap_CS_fsm_state2;
reg   [0:0] e_to_m_d_i_is_op_imm_load_reg_3605;
reg   [0:0] e_to_m_d_i_is_lui_load_reg_3610;
reg   [0:0] e_to_m_d_i_is_ret_load_reg_3615;
reg   [0:0] e_to_m_d_i_is_jal_load_reg_3620;
reg   [0:0] e_to_m_d_i_is_jalr_load_reg_3625;
reg   [0:0] e_to_m_d_i_is_load_load_reg_3631;
reg  signed [19:0] f_to_e_d_i_imm_reg_3637;
reg   [2:0] f_to_e_d_i_type_reg_3642;
reg   [14:0] f_to_e_pc_reg_3646;
reg   [4:0] f_to_e_d_i_rd_reg_3651;
wire   [14:0] f_to_f_fu_1763_p2;
reg   [14:0] f_to_f_reg_3658;
reg   [31:0] instruction_reg_3663;
wire   [4:0] f_to_e_d_i_rd_1_fu_1778_p4;
reg   [4:0] f_to_e_d_i_rd_1_reg_3677;
reg   [7:0] d_imm_inst_19_12_reg_3683;
reg   [2:0] f_to_e_d_i_func3_1_reg_3688;
reg   [4:0] f_to_e_d_i_rs1_1_reg_3693;
reg   [4:0] f_to_e_d_i_rs2_1_reg_3700;
wire   [0:0] f_to_e_d_i_is_jal_fu_1852_p2;
reg   [0:0] f_to_e_d_i_is_jal_reg_3707;
reg   [1:0] opch_reg_3712;
reg   [2:0] opcl_reg_3716;
reg   [0:0] e_to_m_d_i_is_r_type_load_reg_3720;
wire   [0:0] taken_branch_fu_2001_p2;
reg   [0:0] taken_branch_reg_3725;
wire  signed [31:0] sext_ln82_fu_2007_p1;
reg  signed [31:0] sext_ln82_reg_3730;
wire   [31:0] result_12_fu_2033_p2;
wire   [31:0] result_11_fu_2052_p3;
reg   [31:0] result_11_reg_3740;
wire   [31:0] result_8_fu_2060_p2;
wire   [31:0] zext_ln55_fu_2070_p1;
wire   [31:0] zext_ln53_fu_2079_p1;
wire   [31:0] result_5_fu_2087_p2;
reg   [31:0] result_5_reg_3760;
wire   [31:0] result_4_fu_2108_p3;
wire   [31:0] result_fu_2116_p2;
wire   [14:0] npc_fu_2121_p2;
reg   [14:0] npc_reg_3775;
wire   [14:0] j_b_target_pc_fu_2137_p2;
reg   [14:0] j_b_target_pc_reg_3783;
reg   [14:0] i_target_pc_reg_3789;
wire   [0:0] xor_ln92_1_fu_2170_p2;
reg   [0:0] xor_ln92_1_reg_3794;
wire   [0:0] xor_ln94_3_fu_2194_p2;
reg   [0:0] xor_ln94_3_reg_3800;
wire   [31:0] m_to_w_result_fu_2397_p17;
reg   [31:0] m_to_w_result_reg_3805;
wire   [0:0] e_to_f_set_pc_fu_2726_p2;
reg   [0:0] ap_phi_mux_e_to_e_1_phi_fu_603_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4;
reg   [0:0] ap_phi_mux_m_to_w_cancel_1_phi_fu_626_p4;
reg   [0:0] ap_phi_mux_f7_6_phi_fu_639_p4;
reg   [0:0] ap_phi_mux_result_25_phi_fu_650_p14;
wire   [0:0] xor_ln29_fu_1994_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_result_25_reg_646;
wire   [0:0] grp_fu_810_p2;
wire   [0:0] xor_ln23_fu_1977_p2;
wire   [0:0] grp_fu_815_p2;
wire   [0:0] icmp_ln16_fu_1984_p2;
wire   [0:0] icmp_ln14_fu_1989_p2;
reg   [2:0] ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26;
reg   [19:0] ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12;
wire   [19:0] f_to_e_d_i_imm_1_fu_2553_p5;
wire   [19:0] ap_phi_reg_pp0_iter0_f_to_e_d_i_imm_6_reg_713;
wire  signed [19:0] sext_ln41_fu_2487_p1;
wire  signed [19:0] sext_ln40_fu_2508_p1;
wire  signed [19:0] sext_ln39_fu_2522_p1;
reg   [31:0] ap_phi_mux_result_26_phi_fu_734_p16;
reg   [31:0] ap_phi_reg_pp0_iter0_result_26_reg_731;
reg   [31:0] ap_phi_mux_result_27_phi_fu_755_p12;
wire   [31:0] zext_ln109_fu_2614_p1;
wire   [31:0] ap_phi_reg_pp0_iter0_result_27_reg_752;
wire   [31:0] result_17_fu_2593_p3;
wire   [31:0] grp_fu_820_p2;
wire   [31:0] zext_ln86_fu_2609_p1;
wire   [31:0] result_19_fu_2601_p3;
reg   [14:0] ap_phi_mux_next_pc_phi_fu_773_p8;
wire   [14:0] ap_phi_reg_pp0_iter0_next_pc_reg_770;
wire   [14:0] select_ln139_fu_2631_p3;
wire   [14:0] select_ln133_fu_2638_p3;
reg   [0:0] ap_phi_mux_empty_phi_fu_786_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_empty_reg_783;
wire   [0:0] or_ln98_fu_2669_p2;
wire   [0:0] and_ln100_fu_2705_p2;
wire   [0:0] and_ln99_fu_2685_p2;
reg   [14:0] ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6;
wire   [14:0] ap_phi_reg_pp0_iter0_e_to_f_target_pc_3_reg_797;
wire   [63:0] zext_ln8_fu_1150_p1;
wire   [63:0] zext_ln18_fu_1629_p1;
reg   [0:0] w_from_m_has_no_dest_fu_294;
reg   [0:0] is_ret_fu_298;
reg   [0:0] m_to_w_has_no_dest_fu_302;
reg   [0:0] m_to_w_is_ret_fu_306;
reg   [0:0] m_from_e_d_i_is_store_fu_310;
reg   [0:0] m_from_e_d_i_is_load_fu_314;
reg   [0:0] e_to_m_d_i_is_r_type_fu_318;
wire   [0:0] f_to_e_d_i_is_r_type_fu_2432_p2;
reg   [0:0] e_to_m_d_i_has_no_dest_fu_322;
wire   [0:0] f_to_e_d_i_has_no_dest_fu_1888_p2;
reg   [0:0] e_to_m_d_i_is_op_imm_fu_326;
wire   [0:0] f_to_e_d_i_is_op_imm_fu_1870_p2;
reg   [0:0] e_to_m_d_i_is_lui_fu_330;
wire   [0:0] f_to_e_d_i_is_lui_fu_1864_p2;
reg   [0:0] e_to_m_d_i_is_ret_fu_334;
wire   [0:0] f_to_e_d_i_is_ret_fu_1858_p2;
reg   [0:0] e_to_m_d_i_is_jal_fu_338;
reg   [0:0] e_to_m_d_i_is_jalr_fu_342;
wire   [0:0] f_to_e_d_i_is_jalr_fu_1846_p2;
reg   [0:0] e_to_m_d_i_is_branch_fu_346;
wire   [0:0] f_to_e_d_i_is_branch_fu_1840_p2;
reg   [0:0] e_to_m_d_i_is_store_fu_350;
wire   [0:0] f_to_e_d_i_is_store_fu_1834_p2;
reg   [0:0] e_to_m_d_i_is_load_fu_354;
wire   [0:0] f_to_e_d_i_is_load_fu_1828_p2;
reg   [31:0] counter_nbc_fu_358;
wire   [31:0] add_ln53_fu_2920_p2;
reg   [31:0] counter_nbi_fu_362;
wire   [31:0] c_nbi_fu_2881_p2;
reg   [4:0] w_from_m_rd_fu_366;
reg   [2:0] msize_fu_370;
reg   [31:0] e_to_m_rv2_1_fu_374;
reg   [31:0] m_from_e_result_fu_378;
wire   [31:0] e_to_m_result_fu_2736_p3;
reg   [14:0] f_from_e_target_pc_fu_382;
wire   [14:0] e_to_f_target_pc_fu_825_p1;
reg   [14:0] ap_sig_allocacmp_e_to_f_target_pc_4;
reg   [19:0] e_to_m_d_i_imm_fu_386;
reg   [2:0] e_to_m_d_i_type_fu_390;
reg   [4:0] e_to_m_d_i_rs2_fu_394;
reg   [4:0] e_to_m_d_i_rs1_fu_398;
reg   [14:0] pc_1_fu_402;
reg   [14:0] f_to_f_1_fu_406;
reg   [31:0] reg_file_fu_410;
reg    ap_predicate_pred566_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_32;
reg   [31:0] reg_file_1_fu_414;
reg    ap_predicate_pred575_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_33;
reg   [31:0] reg_file_2_fu_418;
reg    ap_predicate_pred584_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_34;
reg   [31:0] reg_file_3_fu_422;
reg    ap_predicate_pred593_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_35;
reg   [31:0] reg_file_4_fu_426;
reg    ap_predicate_pred602_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_36;
reg   [31:0] reg_file_5_fu_430;
reg    ap_predicate_pred611_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_37;
reg   [31:0] reg_file_6_fu_434;
reg    ap_predicate_pred620_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_38;
reg   [31:0] reg_file_7_fu_438;
reg    ap_predicate_pred629_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_39;
reg   [31:0] reg_file_8_fu_442;
reg    ap_predicate_pred638_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_40;
reg   [31:0] reg_file_9_fu_446;
reg    ap_predicate_pred647_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_41;
reg   [31:0] reg_file_10_fu_450;
reg    ap_predicate_pred656_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_42;
reg   [31:0] reg_file_11_fu_454;
reg    ap_predicate_pred665_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_43;
reg   [31:0] reg_file_12_fu_458;
reg    ap_predicate_pred674_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_44;
reg   [31:0] reg_file_13_fu_462;
reg    ap_predicate_pred683_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_45;
reg   [31:0] reg_file_14_fu_466;
reg    ap_predicate_pred692_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_46;
reg   [31:0] reg_file_15_fu_470;
reg    ap_predicate_pred701_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_47;
reg   [31:0] reg_file_16_fu_474;
reg    ap_predicate_pred710_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_48;
reg   [31:0] reg_file_17_fu_478;
reg    ap_predicate_pred719_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_49;
reg   [31:0] reg_file_18_fu_482;
reg    ap_predicate_pred728_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_50;
reg   [31:0] reg_file_19_fu_486;
reg    ap_predicate_pred737_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_51;
reg   [31:0] reg_file_20_fu_490;
reg    ap_predicate_pred746_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_52;
reg   [31:0] reg_file_21_fu_494;
reg    ap_predicate_pred755_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_53;
reg   [31:0] reg_file_22_fu_498;
reg    ap_predicate_pred764_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_54;
reg   [31:0] reg_file_23_fu_502;
reg    ap_predicate_pred773_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_55;
reg   [31:0] reg_file_24_fu_506;
reg    ap_predicate_pred782_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_56;
reg   [31:0] reg_file_25_fu_510;
reg    ap_predicate_pred791_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_57;
reg   [31:0] reg_file_26_fu_514;
reg    ap_predicate_pred800_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_58;
reg   [31:0] reg_file_27_fu_518;
reg    ap_predicate_pred809_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_59;
reg   [31:0] reg_file_28_fu_522;
reg    ap_predicate_pred818_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_60;
reg   [31:0] reg_file_29_fu_526;
reg    ap_predicate_pred827_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_61;
reg   [31:0] reg_file_30_fu_530;
reg    ap_predicate_pred836_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_62;
reg   [31:0] m_to_w_result_3_fu_534;
reg   [31:0] reg_file_31_fu_538;
reg    ap_predicate_pred849_state3;
reg   [31:0] ap_sig_allocacmp_reg_file_63;
reg   [4:0] m_to_w_rd_fu_542;
reg   [2:0] e_to_m_d_i_func3_fu_546;
reg   [4:0] e_to_m_d_i_rd_fu_550;
reg    code_ram_ce0_local;
reg    data_ram_ce0_local;
reg   [14:0] data_ram_address0_local;
reg   [3:0] data_ram_we0_local;
reg   [31:0] data_ram_d0_local;
wire   [31:0] r1_fu_1170_p65;
wire   [31:0] r2_fu_1306_p65;
wire   [0:0] or_ln30_fu_1442_p2;
wire   [0:0] icmp_ln31_1_fu_1460_p2;
wire   [0:0] xor_ln30_fu_1448_p2;
wire   [0:0] and_ln30_fu_1466_p2;
wire   [0:0] icmp_ln31_fu_1454_p2;
wire   [0:0] or_ln32_fu_1484_p2;
wire   [0:0] icmp_ln33_fu_1496_p2;
wire   [0:0] xor_ln32_1_fu_1490_p2;
wire   [0:0] and_ln32_fu_1502_p2;
wire   [0:0] m_bp_1_fu_1472_p2;
wire   [0:0] w_bp_1_fu_1508_p2;
wire   [0:0] icmp_ln36_1_fu_1526_p2;
wire   [0:0] and_ln35_fu_1532_p2;
wire   [0:0] icmp_ln36_fu_1520_p2;
wire   [0:0] and_ln37_fu_1550_p2;
wire   [0:0] icmp_ln38_fu_1544_p2;
wire   [0:0] m_bp_2_fu_1538_p2;
wire   [0:0] w_bp_2_fu_1556_p2;
wire   [0:0] bypass_rs1_fu_1514_p2;
wire   [31:0] select_ln8_fu_1568_p3;
wire   [31:0] r1_fu_1170_p67;
wire   [0:0] bypass_rs2_fu_1562_p2;
wire   [31:0] select_ln8_1_fu_1588_p3;
wire   [31:0] r2_fu_1306_p67;
wire   [14:0] a2_fu_1619_p4;
wire   [15:0] rv2_01_fu_1645_p1;
wire   [1:0] and_ln_fu_1653_p3;
wire   [3:0] zext_ln79_1_fu_1661_p1;
wire   [4:0] shl_ln79_1_fu_1671_p3;
wire   [31:0] zext_ln79_fu_1649_p1;
wire   [31:0] zext_ln79_2_fu_1679_p1;
wire   [7:0] rv2_0_fu_1641_p1;
wire   [3:0] zext_ln76_1_fu_1693_p1;
wire   [4:0] shl_ln76_1_fu_1703_p3;
wire   [31:0] zext_ln76_fu_1689_p1;
wire   [31:0] zext_ln76_2_fu_1711_p1;
wire   [4:0] f_to_e_d_i_opcode_fu_1768_p4;
wire   [0:0] icmp_ln21_fu_1876_p2;
wire   [0:0] or_ln21_fu_1882_p2;
wire  signed [19:0] sext_ln82_fu_2007_p0;
wire  signed [19:0] trunc_ln81_fu_2011_p0;
wire   [31:0] rs_fu_2015_p3;
wire   [4:0] shift_fu_2022_p1;
wire   [4:0] shift_1_fu_2026_p3;
wire   [31:0] zext_ln60_fu_2038_p1;
wire   [31:0] result_9_fu_2042_p2;
wire   [31:0] result_10_fu_2047_p2;
wire   [0:0] result_7_fu_2065_p2;
wire   [0:0] result_6_fu_2074_p2;
wire   [31:0] zext_ln51_fu_2083_p1;
wire   [0:0] and_ln46_fu_2092_p2;
wire   [31:0] result_2_fu_2098_p2;
wire   [31:0] result_3_fu_2103_p2;
wire  signed [19:0] trunc_ln2_fu_2127_p1;
wire   [14:0] trunc_ln2_fu_2127_p4;
wire   [16:0] trunc_ln81_fu_2011_p1;
wire   [16:0] add_ln127_fu_2143_p2;
wire   [0:0] icmp_ln93_fu_2164_p2;
wire   [0:0] xor_ln92_fu_2158_p2;
wire   [0:0] xor_ln94_1_fu_2182_p2;
wire   [0:0] xor_ln94_2_fu_2188_p2;
wire   [0:0] xor_ln94_fu_2176_p2;
wire   [0:0] icmp_ln31_2_fu_2248_p2;
wire   [0:0] icmp_ln31_3_fu_2253_p2;
wire   [0:0] icmp_ln31_4_fu_2258_p2;
wire   [7:0] b_fu_2273_p2;
wire   [7:0] b_fu_2273_p4;
wire   [7:0] b_fu_2273_p6;
wire   [7:0] b_fu_2273_p8;
wire   [7:0] b_fu_2273_p9;
wire   [2:0] b_fu_2273_p10;
wire  signed [7:0] b_fu_2273_p11;
wire   [15:0] h1_fu_2238_p4;
wire   [15:0] h0_fu_2214_p1;
wire  signed [15:0] h_fu_2305_p3;
wire   [0:0] icmp_ln44_fu_2326_p2;
wire   [0:0] icmp_ln44_1_fu_2337_p2;
wire   [0:0] icmp_ln44_2_fu_2348_p2;
wire   [0:0] icmp_ln44_3_fu_2359_p2;
wire   [0:0] icmp_ln44_4_fu_2370_p2;
wire   [0:0] sel_tmp5_fu_2320_p2;
wire   [0:0] and_ln44_fu_2331_p2;
wire   [0:0] and_ln44_1_fu_2342_p2;
wire   [0:0] and_ln44_2_fu_2353_p2;
wire   [0:0] and_ln44_3_fu_2364_p2;
wire   [0:0] and_ln44_4_fu_2375_p2;
wire   [31:0] m_to_w_result_fu_2397_p4;
wire  signed [31:0] m_to_w_result_fu_2397_p8;
wire  signed [31:0] m_to_w_result_fu_2397_p10;
wire   [31:0] m_to_w_result_fu_2397_p12;
wire   [31:0] m_to_w_result_fu_2397_p15;
wire   [5:0] m_to_w_result_fu_2397_p16;
wire   [0:0] d_imm_inst_31_fu_2438_p3;
wire   [0:0] d_imm_inst_7_fu_2454_p3;
wire   [5:0] tmp_4_fu_2466_p4;
wire   [3:0] d_imm_inst_11_8_fu_2445_p4;
wire   [11:0] f_to_e_d_i_imm_5_fu_2475_p5;
wire   [6:0] tmp_2_fu_2492_p4;
wire   [11:0] f_to_e_d_i_imm_4_fu_2501_p3;
wire   [11:0] f_to_e_d_i_imm_3_fu_2513_p4;
wire   [0:0] tmp_fu_2537_p3;
wire   [9:0] tmp_1_fu_2544_p4;
wire   [14:0] pc4_fu_2572_p2;
wire   [31:0] imm12_fu_2565_p3;
wire   [31:0] zext_ln106_fu_2583_p1;
wire   [31:0] result_16_fu_2587_p2;
wire   [14:0] npc4_fu_2577_p2;
wire   [0:0] or_ln85_fu_2619_p2;
wire   [0:0] xor_ln98_1_fu_2664_p2;
wire   [0:0] icmp_ln93_1_fu_2648_p2;
wire   [0:0] icmp_ln99_fu_2675_p2;
wire   [0:0] and_ln99_1_fu_2679_p2;
wire   [0:0] xor_ln92_2_fu_2644_p2;
wire   [0:0] icmp_ln97_fu_2653_p2;
wire   [0:0] icmp_ln100_fu_2691_p2;
wire   [0:0] and_ln100_2_fu_2699_p2;
wire   [0:0] and_ln100_1_fu_2695_p2;
wire   [0:0] or_ln102_1_fu_2716_p2;
wire   [0:0] or_ln102_fu_2711_p2;
wire   [0:0] or_ln102_2_fu_2720_p2;
wire   [0:0] xor_ln98_fu_2658_p2;
wire   [31:0] zext_ln110_fu_2732_p1;
wire   [31:0] result_21_fu_2623_p3;
wire   [31:0] zext_ln27_fu_2878_p1;
wire   [0:0] icmp_ln21_2_fu_2893_p2;
wire   [0:0] xor_ln21_fu_2888_p2;
wire   [0:0] or_ln21_2_fu_2898_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1922;
wire   [4:0] r1_fu_1170_p1;
wire   [4:0] r1_fu_1170_p3;
wire   [4:0] r1_fu_1170_p5;
wire   [4:0] r1_fu_1170_p7;
wire   [4:0] r1_fu_1170_p9;
wire   [4:0] r1_fu_1170_p11;
wire   [4:0] r1_fu_1170_p13;
wire   [4:0] r1_fu_1170_p15;
wire   [4:0] r1_fu_1170_p17;
wire   [4:0] r1_fu_1170_p19;
wire   [4:0] r1_fu_1170_p21;
wire   [4:0] r1_fu_1170_p23;
wire   [4:0] r1_fu_1170_p25;
wire   [4:0] r1_fu_1170_p27;
wire   [4:0] r1_fu_1170_p29;
wire   [4:0] r1_fu_1170_p31;
wire  signed [4:0] r1_fu_1170_p33;
wire  signed [4:0] r1_fu_1170_p35;
wire  signed [4:0] r1_fu_1170_p37;
wire  signed [4:0] r1_fu_1170_p39;
wire  signed [4:0] r1_fu_1170_p41;
wire  signed [4:0] r1_fu_1170_p43;
wire  signed [4:0] r1_fu_1170_p45;
wire  signed [4:0] r1_fu_1170_p47;
wire  signed [4:0] r1_fu_1170_p49;
wire  signed [4:0] r1_fu_1170_p51;
wire  signed [4:0] r1_fu_1170_p53;
wire  signed [4:0] r1_fu_1170_p55;
wire  signed [4:0] r1_fu_1170_p57;
wire  signed [4:0] r1_fu_1170_p59;
wire  signed [4:0] r1_fu_1170_p61;
wire  signed [4:0] r1_fu_1170_p63;
wire   [4:0] r2_fu_1306_p1;
wire   [4:0] r2_fu_1306_p3;
wire   [4:0] r2_fu_1306_p5;
wire   [4:0] r2_fu_1306_p7;
wire   [4:0] r2_fu_1306_p9;
wire   [4:0] r2_fu_1306_p11;
wire   [4:0] r2_fu_1306_p13;
wire   [4:0] r2_fu_1306_p15;
wire   [4:0] r2_fu_1306_p17;
wire   [4:0] r2_fu_1306_p19;
wire   [4:0] r2_fu_1306_p21;
wire   [4:0] r2_fu_1306_p23;
wire   [4:0] r2_fu_1306_p25;
wire   [4:0] r2_fu_1306_p27;
wire   [4:0] r2_fu_1306_p29;
wire   [4:0] r2_fu_1306_p31;
wire  signed [4:0] r2_fu_1306_p33;
wire  signed [4:0] r2_fu_1306_p35;
wire  signed [4:0] r2_fu_1306_p37;
wire  signed [4:0] r2_fu_1306_p39;
wire  signed [4:0] r2_fu_1306_p41;
wire  signed [4:0] r2_fu_1306_p43;
wire  signed [4:0] r2_fu_1306_p45;
wire  signed [4:0] r2_fu_1306_p47;
wire  signed [4:0] r2_fu_1306_p49;
wire  signed [4:0] r2_fu_1306_p51;
wire  signed [4:0] r2_fu_1306_p53;
wire  signed [4:0] r2_fu_1306_p55;
wire  signed [4:0] r2_fu_1306_p57;
wire  signed [4:0] r2_fu_1306_p59;
wire  signed [4:0] r2_fu_1306_p61;
wire  signed [4:0] r2_fu_1306_p63;
wire  signed [2:0] b_fu_2273_p1;
wire   [2:0] b_fu_2273_p3;
wire   [2:0] b_fu_2273_p5;
wire   [2:0] b_fu_2273_p7;
wire  signed [5:0] m_to_w_result_fu_2397_p1;
wire   [5:0] m_to_w_result_fu_2397_p3;
wire   [5:0] m_to_w_result_fu_2397_p5;
wire   [5:0] m_to_w_result_fu_2397_p7;
wire   [5:0] m_to_w_result_fu_2397_p9;
wire   [5:0] m_to_w_result_fu_2397_p11;
wire   [5:0] m_to_w_result_fu_2397_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 w_from_m_has_no_dest_fu_294 = 1'd0;
#0 is_ret_fu_298 = 1'd0;
#0 m_to_w_has_no_dest_fu_302 = 1'd0;
#0 m_to_w_is_ret_fu_306 = 1'd0;
#0 m_from_e_d_i_is_store_fu_310 = 1'd0;
#0 m_from_e_d_i_is_load_fu_314 = 1'd0;
#0 e_to_m_d_i_is_r_type_fu_318 = 1'd0;
#0 e_to_m_d_i_has_no_dest_fu_322 = 1'd0;
#0 e_to_m_d_i_is_op_imm_fu_326 = 1'd0;
#0 e_to_m_d_i_is_lui_fu_330 = 1'd0;
#0 e_to_m_d_i_is_ret_fu_334 = 1'd0;
#0 e_to_m_d_i_is_jal_fu_338 = 1'd0;
#0 e_to_m_d_i_is_jalr_fu_342 = 1'd0;
#0 e_to_m_d_i_is_branch_fu_346 = 1'd0;
#0 e_to_m_d_i_is_store_fu_350 = 1'd0;
#0 e_to_m_d_i_is_load_fu_354 = 1'd0;
#0 counter_nbc_fu_358 = 32'd0;
#0 counter_nbi_fu_362 = 32'd0;
#0 w_from_m_rd_fu_366 = 5'd0;
#0 msize_fu_370 = 3'd0;
#0 e_to_m_rv2_1_fu_374 = 32'd0;
#0 m_from_e_result_fu_378 = 32'd0;
#0 f_from_e_target_pc_fu_382 = 15'd0;
#0 e_to_m_d_i_imm_fu_386 = 20'd0;
#0 e_to_m_d_i_type_fu_390 = 3'd0;
#0 e_to_m_d_i_rs2_fu_394 = 5'd0;
#0 e_to_m_d_i_rs1_fu_398 = 5'd0;
#0 pc_1_fu_402 = 15'd0;
#0 f_to_f_1_fu_406 = 15'd0;
#0 reg_file_fu_410 = 32'd0;
#0 reg_file_1_fu_414 = 32'd0;
#0 reg_file_2_fu_418 = 32'd0;
#0 reg_file_3_fu_422 = 32'd0;
#0 reg_file_4_fu_426 = 32'd0;
#0 reg_file_5_fu_430 = 32'd0;
#0 reg_file_6_fu_434 = 32'd0;
#0 reg_file_7_fu_438 = 32'd0;
#0 reg_file_8_fu_442 = 32'd0;
#0 reg_file_9_fu_446 = 32'd0;
#0 reg_file_10_fu_450 = 32'd0;
#0 reg_file_11_fu_454 = 32'd0;
#0 reg_file_12_fu_458 = 32'd0;
#0 reg_file_13_fu_462 = 32'd0;
#0 reg_file_14_fu_466 = 32'd0;
#0 reg_file_15_fu_470 = 32'd0;
#0 reg_file_16_fu_474 = 32'd0;
#0 reg_file_17_fu_478 = 32'd0;
#0 reg_file_18_fu_482 = 32'd0;
#0 reg_file_19_fu_486 = 32'd0;
#0 reg_file_20_fu_490 = 32'd0;
#0 reg_file_21_fu_494 = 32'd0;
#0 reg_file_22_fu_498 = 32'd0;
#0 reg_file_23_fu_502 = 32'd0;
#0 reg_file_24_fu_506 = 32'd0;
#0 reg_file_25_fu_510 = 32'd0;
#0 reg_file_26_fu_514 = 32'd0;
#0 reg_file_27_fu_518 = 32'd0;
#0 reg_file_28_fu_522 = 32'd0;
#0 reg_file_29_fu_526 = 32'd0;
#0 reg_file_30_fu_530 = 32'd0;
#0 m_to_w_result_3_fu_534 = 32'd0;
#0 reg_file_31_fu_538 = 32'd0;
#0 m_to_w_rd_fu_542 = 5'd0;
#0 e_to_m_d_i_func3_fu_546 = 3'd0;
#0 e_to_m_d_i_rd_fu_550 = 5'd0;
#0 ap_done_reg = 1'b0;
end

rv32i_pp_ip_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .start_pc(start_pc),
    .nb_instruction(nb_instruction),
    .nb_instruction_ap_vld(nb_instruction_ap_vld),
    .nb_cycle(counter_nbc_fu_358),
    .nb_cycle_ap_vld(nb_cycle_ap_vld),
    .code_ram_address0(code_ram_address0),
    .code_ram_ce0(code_ram_ce0_local),
    .code_ram_q0(code_ram_q0),
    .data_ram_address0(data_ram_address0_local),
    .data_ram_ce0(data_ram_ce0_local),
    .data_ram_we0(data_ram_we0_local),
    .data_ram_d0(data_ram_d0_local),
    .data_ram_q0(data_ram_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

(* dissolve_hierarchy = "yes" *) rv32i_pp_ip_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U1(
    .din0(ap_sig_allocacmp_reg_file_32),
    .din1(ap_sig_allocacmp_reg_file_33),
    .din2(ap_sig_allocacmp_reg_file_34),
    .din3(ap_sig_allocacmp_reg_file_35),
    .din4(ap_sig_allocacmp_reg_file_36),
    .din5(ap_sig_allocacmp_reg_file_37),
    .din6(ap_sig_allocacmp_reg_file_38),
    .din7(ap_sig_allocacmp_reg_file_39),
    .din8(ap_sig_allocacmp_reg_file_40),
    .din9(ap_sig_allocacmp_reg_file_41),
    .din10(ap_sig_allocacmp_reg_file_42),
    .din11(ap_sig_allocacmp_reg_file_43),
    .din12(ap_sig_allocacmp_reg_file_44),
    .din13(ap_sig_allocacmp_reg_file_45),
    .din14(ap_sig_allocacmp_reg_file_46),
    .din15(ap_sig_allocacmp_reg_file_47),
    .din16(ap_sig_allocacmp_reg_file_48),
    .din17(ap_sig_allocacmp_reg_file_49),
    .din18(ap_sig_allocacmp_reg_file_50),
    .din19(ap_sig_allocacmp_reg_file_51),
    .din20(ap_sig_allocacmp_reg_file_52),
    .din21(ap_sig_allocacmp_reg_file_53),
    .din22(ap_sig_allocacmp_reg_file_54),
    .din23(ap_sig_allocacmp_reg_file_55),
    .din24(ap_sig_allocacmp_reg_file_56),
    .din25(ap_sig_allocacmp_reg_file_57),
    .din26(ap_sig_allocacmp_reg_file_58),
    .din27(ap_sig_allocacmp_reg_file_59),
    .din28(ap_sig_allocacmp_reg_file_60),
    .din29(ap_sig_allocacmp_reg_file_61),
    .din30(ap_sig_allocacmp_reg_file_62),
    .din31(ap_sig_allocacmp_reg_file_63),
    .def(r1_fu_1170_p65),
    .sel(e_to_m_d_i_rs1_fu_398),
    .dout(r1_fu_1170_p67)
);

(* dissolve_hierarchy = "yes" *) rv32i_pp_ip_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U2(
    .din0(ap_sig_allocacmp_reg_file_32),
    .din1(ap_sig_allocacmp_reg_file_33),
    .din2(ap_sig_allocacmp_reg_file_34),
    .din3(ap_sig_allocacmp_reg_file_35),
    .din4(ap_sig_allocacmp_reg_file_36),
    .din5(ap_sig_allocacmp_reg_file_37),
    .din6(ap_sig_allocacmp_reg_file_38),
    .din7(ap_sig_allocacmp_reg_file_39),
    .din8(ap_sig_allocacmp_reg_file_40),
    .din9(ap_sig_allocacmp_reg_file_41),
    .din10(ap_sig_allocacmp_reg_file_42),
    .din11(ap_sig_allocacmp_reg_file_43),
    .din12(ap_sig_allocacmp_reg_file_44),
    .din13(ap_sig_allocacmp_reg_file_45),
    .din14(ap_sig_allocacmp_reg_file_46),
    .din15(ap_sig_allocacmp_reg_file_47),
    .din16(ap_sig_allocacmp_reg_file_48),
    .din17(ap_sig_allocacmp_reg_file_49),
    .din18(ap_sig_allocacmp_reg_file_50),
    .din19(ap_sig_allocacmp_reg_file_51),
    .din20(ap_sig_allocacmp_reg_file_52),
    .din21(ap_sig_allocacmp_reg_file_53),
    .din22(ap_sig_allocacmp_reg_file_54),
    .din23(ap_sig_allocacmp_reg_file_55),
    .din24(ap_sig_allocacmp_reg_file_56),
    .din25(ap_sig_allocacmp_reg_file_57),
    .din26(ap_sig_allocacmp_reg_file_58),
    .din27(ap_sig_allocacmp_reg_file_59),
    .din28(ap_sig_allocacmp_reg_file_60),
    .din29(ap_sig_allocacmp_reg_file_61),
    .din30(ap_sig_allocacmp_reg_file_62),
    .din31(ap_sig_allocacmp_reg_file_63),
    .def(r2_fu_1306_p65),
    .sel(e_to_m_d_i_rs2_fu_394),
    .dout(r2_fu_1306_p67)
);

(* dissolve_hierarchy = "yes" *) rv32i_pp_ip_sparsemux_9_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_9_3_8_1_1_U3(
    .din0(b_fu_2273_p2),
    .din1(b_fu_2273_p4),
    .din2(b_fu_2273_p6),
    .din3(b_fu_2273_p8),
    .def(b_fu_2273_p9),
    .sel(b_fu_2273_p10),
    .dout(b_fu_2273_p11)
);

(* dissolve_hierarchy = "yes" *) rv32i_pp_ip_sparsemux_15_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h20 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h10 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h2 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h1 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h0 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_15_6_32_1_1_U4(
    .din0(e_to_m_result_2_reg_3438),
    .din1(m_to_w_result_fu_2397_p4),
    .din2(data_ram_q0),
    .din3(m_to_w_result_fu_2397_p8),
    .din4(m_to_w_result_fu_2397_p10),
    .din5(m_to_w_result_fu_2397_p12),
    .din6(32'd0),
    .def(m_to_w_result_fu_2397_p15),
    .sel(m_to_w_result_fu_2397_p16),
    .dout(m_to_w_result_fu_2397_p17)
);

rv32i_pp_ip_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((f_to_e_d_i_func3_reg_3490 == 3'd0)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= result_4_fu_2108_p3;
        end else if ((f_to_e_d_i_func3_reg_3490 == 3'd2)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= zext_ln53_fu_2079_p1;
        end else if ((f_to_e_d_i_func3_reg_3490 == 3'd3)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= zext_ln55_fu_2070_p1;
        end else if ((f_to_e_d_i_func3_reg_3490 == 3'd4)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= result_8_fu_2060_p2;
        end else if ((f_to_e_d_i_func3_reg_3490 == 3'd6)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= result_12_fu_2033_p2;
        end else if ((f_to_e_d_i_func3_reg_3490 == 3'd7)) begin
            ap_phi_reg_pp0_iter0_result_26_reg_731 <= result_fu_2116_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_nbc_fu_358 <= 32'd1;
    end else if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        counter_nbc_fu_358 <= add_ln53_fu_2920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_nbi_fu_362 <= 32'd0;
    end else if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        counter_nbi_fu_362 <= c_nbi_fu_2881_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        e_to_e_1_reg_600 <= e_to_f_set_pc_fu_2726_p2;
    end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        e_to_e_1_reg_600 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        e_to_m_cancel_1_reg_611 <= e_to_e_1_reg_600;
    end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        e_to_m_cancel_1_reg_611 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        f7_6_reg_635 <= instruction_reg_3663[32'd30];
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        f7_6_reg_635 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        f_from_e_target_pc_fu_382 <= e_to_f_target_pc_fu_825_p1;
    end else if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        f_from_e_target_pc_fu_382 <= ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_to_w_cancel_1_reg_623 <= e_to_m_cancel_1_reg_611;
    end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        m_to_w_cancel_1_reg_623 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_10_fu_450 <= 32'd0;
    end else if (((ap_predicate_pred656_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_10_fu_450 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_11_fu_454 <= 32'd0;
    end else if (((ap_predicate_pred665_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_11_fu_454 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_12_fu_458 <= 32'd0;
    end else if (((ap_predicate_pred674_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_12_fu_458 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_13_fu_462 <= 32'd0;
    end else if (((ap_predicate_pred683_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_13_fu_462 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_14_fu_466 <= 32'd0;
    end else if (((ap_predicate_pred692_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_14_fu_466 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_15_fu_470 <= 32'd0;
    end else if (((ap_predicate_pred701_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_15_fu_470 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_16_fu_474 <= 32'd0;
    end else if (((ap_predicate_pred710_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_16_fu_474 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_17_fu_478 <= 32'd0;
    end else if (((ap_predicate_pred719_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_17_fu_478 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_18_fu_482 <= 32'd0;
    end else if (((ap_predicate_pred728_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_18_fu_482 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_19_fu_486 <= 32'd0;
    end else if (((ap_predicate_pred737_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_19_fu_486 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_1_fu_414 <= 32'd0;
    end else if (((ap_predicate_pred575_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_1_fu_414 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_20_fu_490 <= 32'd0;
    end else if (((ap_predicate_pred746_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_20_fu_490 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_21_fu_494 <= 32'd0;
    end else if (((ap_predicate_pred755_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_21_fu_494 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_22_fu_498 <= 32'd0;
    end else if (((ap_predicate_pred764_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_22_fu_498 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_23_fu_502 <= 32'd0;
    end else if (((ap_predicate_pred773_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_23_fu_502 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_24_fu_506 <= 32'd0;
    end else if (((ap_predicate_pred782_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_24_fu_506 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_25_fu_510 <= 32'd0;
    end else if (((ap_predicate_pred791_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_25_fu_510 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_26_fu_514 <= 32'd0;
    end else if (((ap_predicate_pred800_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_26_fu_514 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_27_fu_518 <= 32'd0;
    end else if (((ap_predicate_pred809_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_27_fu_518 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_28_fu_522 <= 32'd0;
    end else if (((ap_predicate_pred818_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_28_fu_522 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_29_fu_526 <= 32'd0;
    end else if (((ap_predicate_pred827_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_29_fu_526 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_2_fu_418 <= 32'd0;
    end else if (((ap_predicate_pred584_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_2_fu_418 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_30_fu_530 <= 32'd0;
    end else if (((ap_predicate_pred836_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_30_fu_530 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_31_fu_538 <= 32'd0;
    end else if (((ap_predicate_pred849_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_31_fu_538 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_3_fu_422 <= 32'd0;
    end else if (((ap_predicate_pred593_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_3_fu_422 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_4_fu_426 <= 32'd0;
    end else if (((ap_predicate_pred602_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_4_fu_426 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_5_fu_430 <= 32'd0;
    end else if (((ap_predicate_pred611_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_5_fu_430 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_6_fu_434 <= 32'd0;
    end else if (((ap_predicate_pred620_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_6_fu_434 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_7_fu_438 <= 32'd0;
    end else if (((ap_predicate_pred629_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_7_fu_438 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_8_fu_442 <= 32'd0;
    end else if (((ap_predicate_pred638_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_8_fu_442 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_9_fu_446 <= 32'd0;
    end else if (((ap_predicate_pred647_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_9_fu_446 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_file_fu_410 <= 32'd0;
    end else if (((ap_predicate_pred566_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        reg_file_fu_410 <= m_to_w_result_2_reg_3448;
    end
end

always @ (posedge ap_clk) begin
    if (((f_to_e_d_i_func3_reg_3490 == 3'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= icmp_ln14_fu_1989_p2;
    end else if (((f_to_e_d_i_func3_reg_3490 == 3'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= icmp_ln16_fu_1984_p2;
    end else if (((f_to_e_d_i_func3_reg_3490 == 3'd4) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= grp_fu_815_p2;
    end else if (((f_to_e_d_i_func3_reg_3490 == 3'd5) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= xor_ln23_fu_1977_p2;
    end else if (((f_to_e_d_i_func3_reg_3490 == 3'd6) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= grp_fu_810_p2;
    end else if (((f_to_e_d_i_func3_reg_3490 == 3'd7) & (1'b1 == ap_CS_fsm_state2))) begin
        result_25_reg_646 <= xor_ln29_fu_1994_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) | (~(or_ln21_3_fu_2904_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        result_25_reg_646 <= ap_phi_reg_pp0_iter0_result_25_reg_646;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        a01_reg_3554 <= a01_fu_1607_p1;
        a1_reg_3561 <= m_from_e_result_fu_378[32'd1];
        data_ram_addr_reg_3566 <= zext_ln18_fu_1629_p1;
        e_to_m_d_i_rd_3_reg_3485 <= m_to_w_rd_fu_542;
        e_to_m_result_2_reg_3438 <= m_from_e_result_fu_378;
        e_to_m_rv2_1_load_reg_3571 <= e_to_m_rv2_1_fu_374;
        f_to_e_d_i_func3_reg_3490 <= e_to_m_d_i_func3_fu_546;
        f_to_e_d_i_rs2_reg_3443 <= e_to_m_d_i_rs2_fu_394;
        m_from_e_d_i_is_store_fu_310 <= e_to_m_d_i_is_store_fu_350;
        m_from_e_d_i_is_store_load_reg_3430 <= m_from_e_d_i_is_store_fu_310;
        m_to_w_has_no_dest_fu_302 <= e_to_m_d_i_has_no_dest_fu_322;
        m_to_w_rd_3_reg_3434 <= w_from_m_rd_fu_366;
        m_to_w_result_2_reg_3448 <= m_to_w_result_3_fu_534;
        msize_1_reg_3576 <= msize_1_fu_1637_p1;
        msize_load_reg_3545 <= msize_fu_370;
        pc_reg_3495 <= pc_fu_1142_p3;
        rv1_reg_3511 <= rv1_fu_1576_p3;
        rv2_reg_3535 <= rv2_fu_1596_p3;
        shl_ln76_2_reg_3595 <= shl_ln76_2_fu_1715_p2;
        shl_ln76_reg_3590 <= shl_ln76_fu_1697_p2;
        shl_ln79_2_reg_3585 <= shl_ln79_2_fu_1683_p2;
        shl_ln79_reg_3580 <= shl_ln79_fu_1665_p2;
        trunc_ln59_reg_3530 <= trunc_ln59_fu_1584_p1;
        w_from_m_has_no_dest_fu_294 <= m_to_w_has_no_dest_fu_302;
        w_from_m_has_no_dest_load_reg_3426 <= w_from_m_has_no_dest_fu_294;
        xor_ln32_reg_3506 <= xor_ln32_fu_1478_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_predicate_pred566_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd0) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred575_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd1) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred584_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd2) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred593_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd3) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred602_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd4) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred611_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd5) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred620_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd6) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred629_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd7) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred638_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd8) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred647_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd9) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred656_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd10) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred665_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd11) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred674_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd12) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred683_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd13) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred692_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd14) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred701_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd15) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred710_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd16) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred719_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd17) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred728_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd18) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred737_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd19) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred746_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd20) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred755_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd21) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred764_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd22) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred773_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd23) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred782_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd24) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred791_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd25) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred800_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd26) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred809_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd27) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred818_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd28) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred827_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd29) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred836_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd30) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        ap_predicate_pred849_state3 <= ((m_to_w_rd_3_reg_3434 == 5'd31) & (w_from_m_has_no_dest_load_reg_3426 == 1'd0) & (m_to_w_cancel_1_reg_623 == 1'd0));
        d_imm_inst_19_12_reg_3683 <= {{code_ram_q0[19:12]}};
        e_to_m_d_i_has_no_dest_fu_322 <= f_to_e_d_i_has_no_dest_fu_1888_p2;
        e_to_m_d_i_is_branch_fu_346 <= f_to_e_d_i_is_branch_fu_1840_p2;
        e_to_m_d_i_is_jal_fu_338 <= f_to_e_d_i_is_jal_fu_1852_p2;
        e_to_m_d_i_is_jal_load_reg_3620 <= e_to_m_d_i_is_jal_fu_338;
        e_to_m_d_i_is_jalr_fu_342 <= f_to_e_d_i_is_jalr_fu_1846_p2;
        e_to_m_d_i_is_jalr_load_reg_3625 <= e_to_m_d_i_is_jalr_fu_342;
        e_to_m_d_i_is_load_fu_354 <= f_to_e_d_i_is_load_fu_1828_p2;
        e_to_m_d_i_is_load_load_reg_3631 <= e_to_m_d_i_is_load_fu_354;
        e_to_m_d_i_is_lui_fu_330 <= f_to_e_d_i_is_lui_fu_1864_p2;
        e_to_m_d_i_is_lui_load_reg_3610 <= e_to_m_d_i_is_lui_fu_330;
        e_to_m_d_i_is_op_imm_fu_326 <= f_to_e_d_i_is_op_imm_fu_1870_p2;
        e_to_m_d_i_is_op_imm_load_reg_3605 <= e_to_m_d_i_is_op_imm_fu_326;
        e_to_m_d_i_is_r_type_load_reg_3720 <= e_to_m_d_i_is_r_type_fu_318;
        e_to_m_d_i_is_ret_fu_334 <= f_to_e_d_i_is_ret_fu_1858_p2;
        e_to_m_d_i_is_ret_load_reg_3615 <= e_to_m_d_i_is_ret_fu_334;
        e_to_m_d_i_is_store_fu_350 <= f_to_e_d_i_is_store_fu_1834_p2;
        f_to_e_d_i_func3_1_reg_3688 <= {{code_ram_q0[14:12]}};
        f_to_e_d_i_imm_reg_3637 <= e_to_m_d_i_imm_fu_386;
        f_to_e_d_i_is_jal_reg_3707 <= f_to_e_d_i_is_jal_fu_1852_p2;
        f_to_e_d_i_rd_1_reg_3677 <= {{code_ram_q0[11:7]}};
        f_to_e_d_i_rd_reg_3651 <= e_to_m_d_i_rd_fu_550;
        f_to_e_d_i_rs1_1_reg_3693 <= {{code_ram_q0[19:15]}};
        f_to_e_d_i_rs2_1_reg_3700 <= {{code_ram_q0[24:20]}};
        f_to_e_d_i_type_reg_3642 <= e_to_m_d_i_type_fu_390;
        f_to_e_pc_reg_3646 <= pc_1_fu_402;
        f_to_f_reg_3658 <= f_to_f_fu_1763_p2;
        i_target_pc_reg_3789 <= {{add_ln127_fu_2143_p2[16:2]}};
        instruction_reg_3663 <= code_ram_q0;
        is_ret_fu_298 <= m_to_w_is_ret_fu_306;
        is_ret_load_reg_3600 <= is_ret_fu_298;
        j_b_target_pc_reg_3783 <= j_b_target_pc_fu_2137_p2;
        m_from_e_d_i_is_load_fu_314 <= e_to_m_d_i_is_load_fu_354;
        m_to_w_is_ret_fu_306 <= e_to_m_d_i_is_ret_fu_334;
        m_to_w_result_reg_3805 <= m_to_w_result_fu_2397_p17;
        npc_reg_3775 <= npc_fu_2121_p2;
        opch_reg_3712 <= {{code_ram_q0[6:5]}};
        opcl_reg_3716 <= {{code_ram_q0[4:2]}};
        result_11_reg_3740 <= result_11_fu_2052_p3;
        result_5_reg_3760 <= result_5_fu_2087_p2;
        sext_ln82_reg_3730 <= sext_ln82_fu_2007_p1;
        taken_branch_reg_3725 <= taken_branch_fu_2001_p2;
        xor_ln92_1_reg_3794 <= xor_ln92_1_fu_2170_p2;
        xor_ln94_3_reg_3800 <= xor_ln94_3_fu_2194_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        e_to_m_d_i_func3_fu_546 <= f_to_e_d_i_func3_1_reg_3688;
        e_to_m_d_i_imm_fu_386 <= ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12;
        e_to_m_d_i_rd_fu_550 <= f_to_e_d_i_rd_1_reg_3677;
        e_to_m_d_i_rs1_fu_398 <= f_to_e_d_i_rs1_1_reg_3693;
        e_to_m_d_i_rs2_fu_394 <= f_to_e_d_i_rs2_1_reg_3700;
        e_to_m_d_i_type_fu_390 <= ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26;
        e_to_m_rv2_1_fu_374 <= rv2_reg_3535;
        f_to_f_1_fu_406 <= f_to_f_reg_3658;
        m_from_e_result_fu_378 <= e_to_m_result_fu_2736_p3;
        m_to_w_rd_fu_542 <= f_to_e_d_i_rd_reg_3651;
        msize_fu_370 <= f_to_e_d_i_func3_reg_3490;
        pc_1_fu_402 <= pc_reg_3495;
        w_from_m_rd_fu_366 <= e_to_m_d_i_rd_3_reg_3485;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        e_to_m_d_i_is_r_type_fu_318 <= f_to_e_d_i_is_r_type_fu_2432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        m_to_w_result_3_fu_534 <= m_to_w_result_reg_3805;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((or_ln21_3_fu_2904_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_e_to_e_1_phi_fu_603_p4 = 1'd1;
    end else begin
        ap_phi_mux_e_to_e_1_phi_fu_603_p4 = e_to_e_1_reg_600;
    end
end

always @ (*) begin
    if (((or_ln98_fu_2669_p2 == 1'd1) | ((or_ln98_fu_2669_p2 == 1'd0) & (1'd0 == and_ln99_fu_2685_p2) & (1'd0 == and_ln100_fu_2705_p2)))) begin
        ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6 = ap_phi_mux_next_pc_phi_fu_773_p8;
    end else if ((((or_ln98_fu_2669_p2 == 1'd0) & (1'd1 == and_ln99_fu_2685_p2)) | ((or_ln98_fu_2669_p2 == 1'd0) & (1'd1 == and_ln100_fu_2705_p2)))) begin
        ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6 = npc_reg_3775;
    end else begin
        ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6 = ap_phi_reg_pp0_iter0_e_to_f_target_pc_3_reg_797;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4 = 1'd1;
    end else begin
        ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4 = e_to_m_cancel_1_reg_611;
    end
end

always @ (*) begin
    if (((or_ln98_fu_2669_p2 == 1'd1) | ((or_ln98_fu_2669_p2 == 1'd0) & (1'd0 == and_ln99_fu_2685_p2) & (1'd0 == and_ln100_fu_2705_p2)))) begin
        ap_phi_mux_empty_phi_fu_786_p6 = 1'd0;
    end else if ((((or_ln98_fu_2669_p2 == 1'd0) & (1'd1 == and_ln99_fu_2685_p2)) | ((or_ln98_fu_2669_p2 == 1'd0) & (1'd1 == and_ln100_fu_2705_p2)))) begin
        ap_phi_mux_empty_phi_fu_786_p6 = 1'd1;
    end else begin
        ap_phi_mux_empty_phi_fu_786_p6 = ap_phi_reg_pp0_iter0_empty_reg_783;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_f7_6_phi_fu_639_p4 = 1'd0;
    end else begin
        ap_phi_mux_f7_6_phi_fu_639_p4 = f7_6_reg_635;
    end
end

always @ (*) begin
    if ((~(ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd2) & ~(ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd3) & ~(ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd4) & ~(ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd5) & ~(ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd6))) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = 20'd0;
    end else if ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd2)) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = sext_ln39_fu_2522_p1;
    end else if ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd3)) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = sext_ln40_fu_2508_p1;
    end else if ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd4)) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = sext_ln41_fu_2487_p1;
    end else if ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd5)) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = {{instruction_reg_3663[31:12]}};
    end else if ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd6)) begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = f_to_e_d_i_imm_1_fu_2553_p5;
    end else begin
        ap_phi_mux_f_to_e_d_i_imm_6_phi_fu_716_p12 = ap_phi_reg_pp0_iter0_f_to_e_d_i_imm_6_reg_713;
    end
end

always @ (*) begin
    if (((opcl_reg_3716 == 3'd0) & (opch_reg_3712 == 2'd1))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd3;
    end else if (((opcl_reg_3716 == 3'd4) & (opch_reg_3712 == 2'd1))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd1;
    end else if ((((opcl_reg_3716 == 3'd5) & (opch_reg_3712 == 2'd0)) | ((opcl_reg_3716 == 3'd5) & (opch_reg_3712 == 2'd1)))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd5;
    end else if (((opcl_reg_3716 == 3'd0) & (opch_reg_3712 == 2'd3))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd4;
    end else if ((((opcl_reg_3716 == 3'd4) & (opch_reg_3712 == 2'd0)) | ((opcl_reg_3716 == 3'd0) & (opch_reg_3712 == 2'd0)) | ((opcl_reg_3716 == 3'd1) & (opch_reg_3712 == 2'd3)))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd2;
    end else if (((opcl_reg_3716 == 3'd3) & (opch_reg_3712 == 2'd3))) begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd6;
    end else begin
        ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 = 3'd7;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_m_to_w_cancel_1_phi_fu_626_p4 = 1'd1;
    end else begin
        ap_phi_mux_m_to_w_cancel_1_phi_fu_626_p4 = m_to_w_cancel_1_reg_623;
    end
end

always @ (*) begin
    if ((~(f_to_e_d_i_type_reg_3642 == 3'd4) & ~(f_to_e_d_i_type_reg_3642 == 3'd2) & ~(f_to_e_d_i_type_reg_3642 == 3'd6))) begin
        ap_phi_mux_next_pc_phi_fu_773_p8 = npc_reg_3775;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd2)) begin
        ap_phi_mux_next_pc_phi_fu_773_p8 = select_ln133_fu_2638_p3;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd4)) begin
        ap_phi_mux_next_pc_phi_fu_773_p8 = select_ln139_fu_2631_p3;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd6)) begin
        ap_phi_mux_next_pc_phi_fu_773_p8 = j_b_target_pc_reg_3783;
    end else begin
        ap_phi_mux_next_pc_phi_fu_773_p8 = ap_phi_reg_pp0_iter0_next_pc_reg_770;
    end
end

always @ (*) begin
    if ((f_to_e_d_i_func3_reg_3490 == 3'd0)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = icmp_ln14_fu_1989_p2;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd1)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = icmp_ln16_fu_1984_p2;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd4)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = grp_fu_815_p2;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd5)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = xor_ln23_fu_1977_p2;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd6)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = grp_fu_810_p2;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd7)) begin
        ap_phi_mux_result_25_phi_fu_650_p14 = xor_ln29_fu_1994_p2;
    end else begin
        ap_phi_mux_result_25_phi_fu_650_p14 = 1'd0;
    end
end

always @ (*) begin
    if ((f_to_e_d_i_func3_reg_3490 == 3'd1)) begin
        ap_phi_mux_result_26_phi_fu_734_p16 = result_5_reg_3760;
    end else if ((f_to_e_d_i_func3_reg_3490 == 3'd5)) begin
        ap_phi_mux_result_26_phi_fu_734_p16 = result_11_reg_3740;
    end else begin
        ap_phi_mux_result_26_phi_fu_734_p16 = ap_phi_reg_pp0_iter0_result_26_reg_731;
    end
end

always @ (*) begin
    if ((~(f_to_e_d_i_type_reg_3642 == 3'd2) & ~(f_to_e_d_i_type_reg_3642 == 3'd3) & ~(f_to_e_d_i_type_reg_3642 == 3'd5) & ~(f_to_e_d_i_type_reg_3642 == 3'd6))) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = 32'd0;
    end else if (((f_to_e_d_i_type_reg_3642 == 3'd2) & (e_to_m_d_i_is_jalr_load_reg_3625 == 1'd0))) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = result_19_fu_2601_p3;
    end else if (((f_to_e_d_i_type_reg_3642 == 3'd2) & (e_to_m_d_i_is_jalr_load_reg_3625 == 1'd1))) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = zext_ln86_fu_2609_p1;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd3)) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = grp_fu_820_p2;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd5)) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = result_17_fu_2593_p3;
    end else if ((f_to_e_d_i_type_reg_3642 == 3'd6)) begin
        ap_phi_mux_result_27_phi_fu_755_p12 = zext_ln109_fu_2614_p1;
    end else begin
        ap_phi_mux_result_27_phi_fu_755_p12 = ap_phi_reg_pp0_iter0_result_27_reg_752;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_e_to_f_target_pc_4 = e_to_f_target_pc_fu_825_p1;
    end else begin
        ap_sig_allocacmp_e_to_f_target_pc_4 = f_from_e_target_pc_fu_382;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_32 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_32 = reg_file_fu_410;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_33 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_33 = reg_file_1_fu_414;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_34 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_34 = reg_file_2_fu_418;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_35 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_35 = reg_file_3_fu_422;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_36 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_36 = reg_file_4_fu_426;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_37 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_37 = reg_file_5_fu_430;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_38 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_38 = reg_file_6_fu_434;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_39 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_39 = reg_file_7_fu_438;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_40 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_40 = reg_file_8_fu_442;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_41 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_41 = reg_file_9_fu_446;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_42 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_42 = reg_file_10_fu_450;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_43 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_43 = reg_file_11_fu_454;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_44 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_44 = reg_file_12_fu_458;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_45 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_45 = reg_file_13_fu_462;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_46 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_46 = reg_file_14_fu_466;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_47 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_47 = reg_file_15_fu_470;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_48 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_48 = reg_file_16_fu_474;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_49 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_49 = reg_file_17_fu_478;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_50 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_50 = reg_file_18_fu_482;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_51 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_51 = reg_file_19_fu_486;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_52 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_52 = reg_file_20_fu_490;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_53 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_53 = reg_file_21_fu_494;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_54 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_54 = reg_file_22_fu_498;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_55 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_55 = reg_file_23_fu_502;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_56 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_56 = reg_file_24_fu_506;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_57 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_57 = reg_file_25_fu_510;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_58 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_58 = reg_file_26_fu_514;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_59 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_59 = reg_file_27_fu_518;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_60 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_60 = reg_file_28_fu_522;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_61 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_61 = reg_file_29_fu_526;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_62 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_62 = reg_file_30_fu_530;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_reg_file_63 = 32'd0;
    end else begin
        ap_sig_allocacmp_reg_file_63 = reg_file_31_fu_538;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        code_ram_ce0_local = 1'b1;
    end else begin
        code_ram_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd0)) | ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd1)) | ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd2)))) begin
        data_ram_address0_local = data_ram_addr_reg_3566;
    end else if (((ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_ram_address0_local = zext_ln18_fu_1629_p1;
    end else begin
        data_ram_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd0)) | ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd1)) | ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (msize_1_reg_3576 == 2'd2)) | ((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_ram_ce0_local = 1'b1;
    end else begin
        data_ram_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1922)) begin
        if ((msize_1_reg_3576 == 2'd0)) begin
            data_ram_d0_local = shl_ln76_2_reg_3595;
        end else if ((msize_1_reg_3576 == 2'd1)) begin
            data_ram_d0_local = shl_ln79_2_reg_3585;
        end else if ((msize_1_reg_3576 == 2'd2)) begin
            data_ram_d0_local = e_to_m_rv2_1_load_reg_3571;
        end else begin
            data_ram_d0_local = 'bx;
        end
    end else begin
        data_ram_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1922)) begin
        if ((msize_1_reg_3576 == 2'd0)) begin
            data_ram_we0_local = shl_ln76_reg_3590;
        end else if ((msize_1_reg_3576 == 2'd1)) begin
            data_ram_we0_local = shl_ln79_reg_3580;
        end else if ((msize_1_reg_3576 == 2'd2)) begin
            data_ram_we0_local = 4'd15;
        end else begin
            data_ram_we0_local = 4'd0;
        end
    end else begin
        data_ram_we0_local = 4'd0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_ln21_3_fu_2904_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        nb_cycle_ap_vld = 1'b1;
    end else begin
        nb_cycle_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_ln21_3_fu_2904_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        nb_instruction_ap_vld = 1'b1;
    end else begin
        nb_instruction_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a01_fu_1607_p1 = m_from_e_result_fu_378[1:0];

assign a1_fu_1611_p3 = m_from_e_result_fu_378[32'd1];

assign a2_fu_1619_p4 = {{m_from_e_result_fu_378[16:2]}};

assign add_ln127_fu_2143_p2 = (trunc_ln59_reg_3530 + trunc_ln81_fu_2011_p1);

assign add_ln53_fu_2920_p2 = (counter_nbc_fu_358 + 32'd1);

assign and_ln100_1_fu_2695_p2 = (xor_ln94_3_reg_3800 & xor_ln92_1_reg_3794);

assign and_ln100_2_fu_2699_p2 = (icmp_ln97_fu_2653_p2 & icmp_ln100_fu_2691_p2);

assign and_ln100_fu_2705_p2 = (and_ln100_2_fu_2699_p2 & and_ln100_1_fu_2695_p2);

assign and_ln30_fu_1466_p2 = (xor_ln30_fu_1448_p2 & icmp_ln31_1_fu_1460_p2);

assign and_ln32_fu_1502_p2 = (xor_ln32_1_fu_1490_p2 & icmp_ln33_fu_1496_p2);

assign and_ln35_fu_1532_p2 = (xor_ln30_fu_1448_p2 & icmp_ln36_1_fu_1526_p2);

assign and_ln37_fu_1550_p2 = (xor_ln32_1_fu_1490_p2 & icmp_ln36_fu_1520_p2);

assign and_ln44_1_fu_2342_p2 = (m_from_e_d_i_is_load_fu_314 & icmp_ln44_1_fu_2337_p2);

assign and_ln44_2_fu_2353_p2 = (m_from_e_d_i_is_load_fu_314 & icmp_ln44_2_fu_2348_p2);

assign and_ln44_3_fu_2364_p2 = (m_from_e_d_i_is_load_fu_314 & icmp_ln44_3_fu_2359_p2);

assign and_ln44_4_fu_2375_p2 = (m_from_e_d_i_is_load_fu_314 & icmp_ln44_4_fu_2370_p2);

assign and_ln44_fu_2331_p2 = (m_from_e_d_i_is_load_fu_314 & icmp_ln44_fu_2326_p2);

assign and_ln46_fu_2092_p2 = (e_to_m_d_i_is_r_type_fu_318 & ap_phi_mux_f7_6_phi_fu_639_p4);

assign and_ln99_1_fu_2679_p2 = (icmp_ln99_fu_2675_p2 & icmp_ln93_1_fu_2648_p2);

assign and_ln99_fu_2685_p2 = (xor_ln92_2_fu_2644_p2 & and_ln99_1_fu_2679_p2);

assign and_ln_fu_1653_p3 = {{a1_fu_1611_p3}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_condition_1922 = ((m_from_e_d_i_is_store_load_reg_3430 == 1'd1) & (e_to_m_cancel_1_reg_611 == 1'd0) & (1'b1 == ap_CS_fsm_state2));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_e_to_f_target_pc_3_reg_797 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_reg_783 = 'bx;

assign ap_phi_reg_pp0_iter0_f_to_e_d_i_imm_6_reg_713 = 'bx;

assign ap_phi_reg_pp0_iter0_next_pc_reg_770 = 'bx;

assign ap_phi_reg_pp0_iter0_result_25_reg_646 = 1'd0;

assign ap_phi_reg_pp0_iter0_result_27_reg_752 = 'bx;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b_fu_2273_p10 = {{{icmp_ln31_2_fu_2248_p2}, {icmp_ln31_3_fu_2253_p2}}, {icmp_ln31_4_fu_2258_p2}};

assign b_fu_2273_p2 = {{data_ram_q0[23:16]}};

assign b_fu_2273_p4 = {{data_ram_q0[15:8]}};

assign b_fu_2273_p6 = data_ram_q0[7:0];

assign b_fu_2273_p8 = {{data_ram_q0[31:24]}};

assign b_fu_2273_p9 = 'bx;

assign bypass_rs1_fu_1514_p2 = (w_bp_1_fu_1508_p2 | m_bp_1_fu_1472_p2);

assign bypass_rs2_fu_1562_p2 = (w_bp_2_fu_1556_p2 | m_bp_2_fu_1538_p2);

assign c_nbi_fu_2881_p2 = (zext_ln27_fu_2878_p1 + counter_nbi_fu_362);

assign code_ram_address0 = zext_ln8_fu_1150_p1;

assign d_imm_inst_11_8_fu_2445_p4 = {{instruction_reg_3663[11:8]}};

assign d_imm_inst_31_fu_2438_p3 = instruction_reg_3663[32'd31];

assign d_imm_inst_7_fu_2454_p3 = instruction_reg_3663[32'd7];

assign e_to_f_set_pc_fu_2726_p2 = (xor_ln98_fu_2658_p2 & or_ln102_2_fu_2720_p2);

assign e_to_f_target_pc_fu_825_p1 = start_pc[14:0];

assign e_to_m_result_fu_2736_p3 = ((e_to_m_d_i_is_ret_load_reg_3615[0:0] == 1'b1) ? zext_ln110_fu_2732_p1 : result_21_fu_2623_p3);

assign f_to_e_d_i_func3_load_fu_1139_p1 = e_to_m_d_i_func3_fu_546;

assign f_to_e_d_i_has_no_dest_fu_1888_p2 = (or_ln21_fu_1882_p2 | f_to_e_d_i_is_store_fu_1834_p2);

assign f_to_e_d_i_imm_1_fu_2553_p5 = {{{{d_imm_inst_31_fu_2438_p3}, {d_imm_inst_19_12_reg_3683}}, {tmp_fu_2537_p3}}, {tmp_1_fu_2544_p4}};

assign f_to_e_d_i_imm_3_fu_2513_p4 = {{instruction_reg_3663[31:20]}};

assign f_to_e_d_i_imm_4_fu_2501_p3 = {{tmp_2_fu_2492_p4}, {f_to_e_d_i_rd_1_reg_3677}};

assign f_to_e_d_i_imm_5_fu_2475_p5 = {{{{d_imm_inst_31_fu_2438_p3}, {d_imm_inst_7_fu_2454_p3}}, {tmp_4_fu_2466_p4}}, {d_imm_inst_11_8_fu_2445_p4}};

assign f_to_e_d_i_is_branch_fu_1840_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd24) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_jal_fu_1852_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd27) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_jalr_fu_1846_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd25) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_load_fu_1828_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd0) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_lui_fu_1864_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd13) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_op_imm_fu_1870_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd4) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_r_type_fu_2432_p2 = ((ap_phi_mux_f_to_e_d_i_type_1_phi_fu_672_p26 == 3'd1) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_ret_fu_1858_p2 = ((code_ram_q0 == 32'd32871) ? 1'b1 : 1'b0);

assign f_to_e_d_i_is_store_fu_1834_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd8) ? 1'b1 : 1'b0);

assign f_to_e_d_i_opcode_fu_1768_p4 = {{code_ram_q0[6:2]}};

assign f_to_e_d_i_rd_1_fu_1778_p4 = {{code_ram_q0[11:7]}};

assign f_to_f_fu_1763_p2 = (pc_reg_3495 + 15'd1);

assign grp_fu_810_p2 = ((rv1_reg_3511 < rv2_reg_3535) ? 1'b1 : 1'b0);

assign grp_fu_815_p2 = (($signed(rv1_reg_3511) < $signed(rv2_reg_3535)) ? 1'b1 : 1'b0);

assign grp_fu_820_p2 = ($signed(rv1_reg_3511) + $signed(sext_ln82_reg_3730));

assign h0_fu_2214_p1 = data_ram_q0[15:0];

assign h1_fu_2238_p4 = {{data_ram_q0[31:16]}};

assign h_fu_2305_p3 = ((a1_reg_3561[0:0] == 1'b1) ? h1_fu_2238_p4 : h0_fu_2214_p1);

assign icmp_ln100_fu_2691_p2 = ((f_to_e_d_i_rd_reg_3651 == f_to_e_d_i_rs2_1_reg_3700) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_1989_p2 = ((rv1_reg_3511 == rv2_reg_3535) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_1984_p2 = ((rv1_reg_3511 != rv2_reg_3535) ? 1'b1 : 1'b0);

assign icmp_ln21_2_fu_2893_p2 = ((m_to_w_result_2_reg_3448 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_1876_p2 = ((f_to_e_d_i_rd_1_fu_1778_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_1460_p2 = ((e_to_m_d_i_rs1_fu_398 == m_to_w_rd_fu_542) ? 1'b1 : 1'b0);

assign icmp_ln31_2_fu_2248_p2 = ((a01_reg_3554 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln31_3_fu_2253_p2 = ((a01_reg_3554 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln31_4_fu_2258_p2 = ((a01_reg_3554 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_1454_p2 = ((e_to_m_d_i_rs1_fu_398 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_1496_p2 = ((e_to_m_d_i_rs1_fu_398 == w_from_m_rd_fu_366) ? 1'b1 : 1'b0);

assign icmp_ln36_1_fu_1526_p2 = ((e_to_m_d_i_rs2_fu_394 == m_to_w_rd_fu_542) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_1520_p2 = ((e_to_m_d_i_rs2_fu_394 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_1544_p2 = ((e_to_m_d_i_rs2_fu_394 == w_from_m_rd_fu_366) ? 1'b1 : 1'b0);

assign icmp_ln44_1_fu_2337_p2 = ((msize_load_reg_3545 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln44_2_fu_2348_p2 = ((msize_load_reg_3545 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln44_3_fu_2359_p2 = ((msize_load_reg_3545 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln44_4_fu_2370_p2 = ((msize_load_reg_3545 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_2326_p2 = ((msize_load_reg_3545 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln93_1_fu_2648_p2 = ((f_to_e_d_i_rs1_1_reg_3693 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_2164_p2 = ((f_to_e_d_i_opcode_fu_1768_p4 == 5'd5) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_2653_p2 = ((f_to_e_d_i_rs2_1_reg_3700 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_2675_p2 = ((f_to_e_d_i_rd_reg_3651 == f_to_e_d_i_rs1_1_reg_3693) ? 1'b1 : 1'b0);

assign imm12_fu_2565_p3 = {{f_to_e_d_i_imm_reg_3637}, {12'd0}};

assign j_b_target_pc_fu_2137_p2 = (trunc_ln2_fu_2127_p4 + pc_1_fu_402);

assign m_bp_1_fu_1472_p2 = (icmp_ln31_fu_1454_p2 & and_ln30_fu_1466_p2);

assign m_bp_2_fu_1538_p2 = (icmp_ln36_fu_1520_p2 & and_ln35_fu_1532_p2);

assign m_to_w_result_fu_2397_p10 = b_fu_2273_p11;

assign m_to_w_result_fu_2397_p12 = $unsigned(h_fu_2305_p3);

assign m_to_w_result_fu_2397_p15 = 'bx;

assign m_to_w_result_fu_2397_p16 = {{{{{{sel_tmp5_fu_2320_p2}, {and_ln44_fu_2331_p2}}, {and_ln44_1_fu_2342_p2}}, {and_ln44_2_fu_2353_p2}}, {and_ln44_3_fu_2364_p2}}, {and_ln44_4_fu_2375_p2}};

assign m_to_w_result_fu_2397_p4 = $unsigned(b_fu_2273_p11);

assign m_to_w_result_fu_2397_p8 = h_fu_2305_p3;

assign msize_1_fu_1637_p1 = msize_fu_370[1:0];

assign nb_instruction = (zext_ln27_fu_2878_p1 + counter_nbi_fu_362);

assign npc4_fu_2577_p2 = (pc4_fu_2572_p2 + 15'd4);

assign npc_fu_2121_p2 = (pc_1_fu_402 + 15'd1);

assign or_ln102_1_fu_2716_p2 = (taken_branch_reg_3725 | e_to_m_d_i_is_jalr_load_reg_3625);

assign or_ln102_2_fu_2720_p2 = (or_ln102_fu_2711_p2 | or_ln102_1_fu_2716_p2);

assign or_ln102_fu_2711_p2 = (e_to_m_d_i_is_jal_load_reg_3620 | ap_phi_mux_empty_phi_fu_786_p6);

assign or_ln21_2_fu_2898_p2 = (xor_ln21_fu_2888_p2 | icmp_ln21_2_fu_2893_p2);

assign or_ln21_3_fu_2904_p2 = (or_ln21_2_fu_2898_p2 | m_to_w_cancel_1_reg_623);

assign or_ln21_fu_1882_p2 = (icmp_ln21_fu_1876_p2 | f_to_e_d_i_is_branch_fu_1840_p2);

assign or_ln30_fu_1442_p2 = (m_to_w_has_no_dest_fu_302 | ap_phi_mux_e_to_m_cancel_1_phi_fu_614_p4);

assign or_ln32_fu_1484_p2 = (w_from_m_has_no_dest_fu_294 | ap_phi_mux_m_to_w_cancel_1_phi_fu_626_p4);

assign or_ln85_fu_2619_p2 = (e_to_m_d_i_is_r_type_load_reg_3720 | e_to_m_d_i_is_op_imm_load_reg_3605);

assign or_ln98_fu_2669_p2 = (xor_ln98_1_fu_2664_p2 | e_to_e_1_reg_600);

assign pc4_fu_2572_p2 = f_to_e_pc_reg_3646 << 15'd2;

assign pc_fu_1142_p3 = ((ap_phi_mux_e_to_e_1_phi_fu_603_p4[0:0] == 1'b1) ? ap_sig_allocacmp_e_to_f_target_pc_4 : f_to_f_1_fu_406);

assign r1_fu_1170_p65 = 'bx;

assign r2_fu_1306_p65 = 'bx;

assign result_10_fu_2047_p2 = rv1_reg_3511 >> zext_ln60_fu_2038_p1;

assign result_11_fu_2052_p3 = ((ap_phi_mux_f7_6_phi_fu_639_p4[0:0] == 1'b1) ? result_9_fu_2042_p2 : result_10_fu_2047_p2);

assign result_12_fu_2033_p2 = (rv1_reg_3511 | rs_fu_2015_p3);

assign result_16_fu_2587_p2 = (imm12_fu_2565_p3 + zext_ln106_fu_2583_p1);

assign result_17_fu_2593_p3 = ((e_to_m_d_i_is_lui_load_reg_3610[0:0] == 1'b1) ? imm12_fu_2565_p3 : result_16_fu_2587_p2);

assign result_19_fu_2601_p3 = ((e_to_m_d_i_is_load_load_reg_3631[0:0] == 1'b1) ? grp_fu_820_p2 : 32'd0);

assign result_21_fu_2623_p3 = ((or_ln85_fu_2619_p2[0:0] == 1'b1) ? ap_phi_mux_result_26_phi_fu_734_p16 : ap_phi_mux_result_27_phi_fu_755_p12);

assign result_2_fu_2098_p2 = (rv1_reg_3511 - rs_fu_2015_p3);

assign result_3_fu_2103_p2 = (rs_fu_2015_p3 + rv1_reg_3511);

assign result_4_fu_2108_p3 = ((and_ln46_fu_2092_p2[0:0] == 1'b1) ? result_2_fu_2098_p2 : result_3_fu_2103_p2);

assign result_5_fu_2087_p2 = rv1_reg_3511 << zext_ln51_fu_2083_p1;

assign result_6_fu_2074_p2 = (($signed(rv1_reg_3511) < $signed(rs_fu_2015_p3)) ? 1'b1 : 1'b0);

assign result_7_fu_2065_p2 = ((rv1_reg_3511 < rs_fu_2015_p3) ? 1'b1 : 1'b0);

assign result_8_fu_2060_p2 = (rv1_reg_3511 ^ rs_fu_2015_p3);

assign result_9_fu_2042_p2 = $signed(rv1_reg_3511) >>> zext_ln60_fu_2038_p1;

assign result_fu_2116_p2 = (rv1_reg_3511 & rs_fu_2015_p3);

assign rs_fu_2015_p3 = ((e_to_m_d_i_is_r_type_fu_318[0:0] == 1'b1) ? rv2_reg_3535 : sext_ln82_fu_2007_p1);

assign rv1_fu_1576_p3 = ((bypass_rs1_fu_1514_p2[0:0] == 1'b1) ? select_ln8_fu_1568_p3 : r1_fu_1170_p67);

assign rv2_01_fu_1645_p1 = e_to_m_rv2_1_fu_374[15:0];

assign rv2_0_fu_1641_p1 = e_to_m_rv2_1_fu_374[7:0];

assign rv2_fu_1596_p3 = ((bypass_rs2_fu_1562_p2[0:0] == 1'b1) ? select_ln8_1_fu_1588_p3 : r2_fu_1306_p67);

assign sel_tmp5_fu_2320_p2 = (m_from_e_d_i_is_load_fu_314 ^ 1'd1);

assign select_ln133_fu_2638_p3 = ((e_to_m_d_i_is_jalr_load_reg_3625[0:0] == 1'b1) ? i_target_pc_reg_3789 : npc_reg_3775);

assign select_ln139_fu_2631_p3 = ((result_25_reg_646[0:0] == 1'b1) ? j_b_target_pc_reg_3783 : npc_reg_3775);

assign select_ln8_1_fu_1588_p3 = ((m_bp_2_fu_1538_p2[0:0] == 1'b1) ? m_from_e_result_fu_378 : m_to_w_result_3_fu_534);

assign select_ln8_fu_1568_p3 = ((m_bp_1_fu_1472_p2[0:0] == 1'b1) ? m_from_e_result_fu_378 : m_to_w_result_3_fu_534);

assign sext_ln39_fu_2522_p1 = $signed(f_to_e_d_i_imm_3_fu_2513_p4);

assign sext_ln40_fu_2508_p1 = $signed(f_to_e_d_i_imm_4_fu_2501_p3);

assign sext_ln41_fu_2487_p1 = $signed(f_to_e_d_i_imm_5_fu_2475_p5);

assign sext_ln82_fu_2007_p0 = e_to_m_d_i_imm_fu_386;

assign sext_ln82_fu_2007_p1 = sext_ln82_fu_2007_p0;

assign shift_1_fu_2026_p3 = ((e_to_m_d_i_is_r_type_fu_318[0:0] == 1'b1) ? shift_fu_2022_p1 : f_to_e_d_i_rs2_reg_3443);

assign shift_fu_2022_p1 = rs_fu_2015_p3[4:0];

assign shl_ln76_1_fu_1703_p3 = {{a01_fu_1607_p1}, {3'd0}};

assign shl_ln76_2_fu_1715_p2 = zext_ln76_fu_1689_p1 << zext_ln76_2_fu_1711_p1;

assign shl_ln76_fu_1697_p2 = 4'd1 << zext_ln76_1_fu_1693_p1;

assign shl_ln79_1_fu_1671_p3 = {{a1_fu_1611_p3}, {4'd0}};

assign shl_ln79_2_fu_1683_p2 = zext_ln79_fu_1649_p1 << zext_ln79_2_fu_1679_p1;

assign shl_ln79_fu_1665_p2 = 4'd3 << zext_ln79_1_fu_1661_p1;

assign taken_branch_fu_2001_p2 = (e_to_m_d_i_is_branch_fu_346 & ap_phi_mux_result_25_phi_fu_650_p14);

assign tmp_1_fu_2544_p4 = {{instruction_reg_3663[30:21]}};

assign tmp_2_fu_2492_p4 = {{instruction_reg_3663[31:25]}};

assign tmp_4_fu_2466_p4 = {{instruction_reg_3663[30:25]}};

assign tmp_fu_2537_p3 = instruction_reg_3663[32'd20];

assign trunc_ln2_fu_2127_p1 = e_to_m_d_i_imm_fu_386;

assign trunc_ln2_fu_2127_p4 = {{trunc_ln2_fu_2127_p1[15:1]}};

assign trunc_ln59_fu_1584_p1 = rv1_fu_1576_p3[16:0];

assign trunc_ln81_fu_2011_p0 = e_to_m_d_i_imm_fu_386;

assign trunc_ln81_fu_2011_p1 = trunc_ln81_fu_2011_p0[16:0];

assign w_bp_1_fu_1508_p2 = (icmp_ln31_fu_1454_p2 & and_ln32_fu_1502_p2);

assign w_bp_2_fu_1556_p2 = (icmp_ln38_fu_1544_p2 & and_ln37_fu_1550_p2);

assign xor_ln21_fu_2888_p2 = (is_ret_load_reg_3600 ^ 1'd1);

assign xor_ln23_fu_1977_p2 = (grp_fu_815_p2 ^ 1'd1);

assign xor_ln29_fu_1994_p2 = (grp_fu_810_p2 ^ 1'd1);

assign xor_ln30_fu_1448_p2 = (or_ln30_fu_1442_p2 ^ 1'd1);

assign xor_ln32_1_fu_1490_p2 = (or_ln32_fu_1484_p2 ^ 1'd1);

assign xor_ln32_fu_1478_p2 = (ap_phi_mux_m_to_w_cancel_1_phi_fu_626_p4 ^ 1'd1);

assign xor_ln92_1_fu_2170_p2 = (xor_ln92_fu_2158_p2 ^ icmp_ln93_fu_2164_p2);

assign xor_ln92_2_fu_2644_p2 = (xor_ln92_1_reg_3794 ^ f_to_e_d_i_is_jal_reg_3707);

assign xor_ln92_fu_2158_p2 = (f_to_e_d_i_is_lui_fu_1864_p2 ^ 1'd1);

assign xor_ln94_1_fu_2182_p2 = (f_to_e_d_i_is_jalr_fu_1846_p2 ^ f_to_e_d_i_is_jal_fu_1852_p2);

assign xor_ln94_2_fu_2188_p2 = (xor_ln94_1_fu_2182_p2 ^ f_to_e_d_i_is_load_fu_1828_p2);

assign xor_ln94_3_fu_2194_p2 = (xor_ln94_fu_2176_p2 ^ xor_ln94_2_fu_2188_p2);

assign xor_ln94_fu_2176_p2 = (f_to_e_d_i_is_op_imm_fu_1870_p2 ^ 1'd1);

assign xor_ln98_1_fu_2664_p2 = (e_to_m_d_i_is_load_load_reg_3631 ^ 1'd1);

assign xor_ln98_fu_2658_p2 = (e_to_e_1_reg_600 ^ 1'd1);

assign zext_ln106_fu_2583_p1 = pc4_fu_2572_p2;

assign zext_ln109_fu_2614_p1 = npc4_fu_2577_p2;

assign zext_ln110_fu_2732_p1 = ap_phi_mux_e_to_f_target_pc_3_phi_fu_800_p6;

assign zext_ln18_fu_1629_p1 = a2_fu_1619_p4;

assign zext_ln27_fu_2878_p1 = xor_ln32_reg_3506;

assign zext_ln51_fu_2083_p1 = shift_1_fu_2026_p3;

assign zext_ln53_fu_2079_p1 = result_6_fu_2074_p2;

assign zext_ln55_fu_2070_p1 = result_7_fu_2065_p2;

assign zext_ln60_fu_2038_p1 = shift_1_fu_2026_p3;

assign zext_ln76_1_fu_1693_p1 = a01_fu_1607_p1;

assign zext_ln76_2_fu_1711_p1 = shl_ln76_1_fu_1703_p3;

assign zext_ln76_fu_1689_p1 = rv2_0_fu_1641_p1;

assign zext_ln79_1_fu_1661_p1 = and_ln_fu_1653_p3;

assign zext_ln79_2_fu_1679_p1 = shl_ln79_1_fu_1671_p3;

assign zext_ln79_fu_1649_p1 = rv2_01_fu_1645_p1;

assign zext_ln86_fu_2609_p1 = npc4_fu_2577_p2;

assign zext_ln8_fu_1150_p1 = pc_fu_1142_p3;

endmodule //rv32i_pp_ip
