# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_4h/design_1_4h.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h || ORIG_REF_NAME==design_1_4h} -quiet] -quiet

# IP: bd/design_1_4h/ip/design_1_4h_processing_system7_0_1/design_1_4h_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h_processing_system7_0_1 || ORIG_REF_NAME==design_1_4h_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1_4h/ip/design_1_4h_ps7_0_axi_periph_1/design_1_4h_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_1_4h_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1_4h/ip/design_1_4h_rst_ps7_0_100M_1/design_1_4h_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_1_4h_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/design_1_4h/ip/design_1_4h_auto_pc_0/design_1_4h_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h_auto_pc_0 || ORIG_REF_NAME==design_1_4h_auto_pc_0} -quiet] -quiet

# IP: bd/design_1_4h/ip/design_1_4h_multihart_ip_0_2/design_1_4h_multihart_ip_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_4h_multihart_ip_0_2 || ORIG_REF_NAME==design_1_4h_multihart_ip_0_2} -quiet] -quiet

# XDC: /home/goossens/book-2022.1/new_book_ip/multihart_ip/z1_multihart_4h_ip.gen/sources_1/bd/design_1_4h/design_1_4h_ooc.xdc
