# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.srcs/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0.xci
# IP: The module: 'design_1_multicore_multicycle_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.srcs/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0.xci
# IP: The module: 'design_1_multicore_multicycle_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/goossens/goossens-book-ip-projects/2024.1/pynq_io/pynq_io_multicore_multicycle/pynq_io_multicore_multicycle_design.gen/sources_1/bd/design_1_multicore_multicycle/ip/design_1_multicore_multicycle_axi_gpio_0_0/design_1_multicore_multicycle_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_multicore_multicycle_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
