# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bernard/book-2022.1/new_book_ip/multihart_ip/z1_multihart_8h_ip.srcs/sources_1/bd/design_1_8h/ip/design_1_8h_multihart_ip_0_1/design_1_8h_multihart_ip_0_1.xci
# IP: The module: 'design_1_8h_multihart_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bernard/book-2022.1/new_book_ip/multihart_ip/z1_multihart_8h_ip.gen/sources_1/bd/design_1_8h/ip/design_1_8h_multihart_ip_0_1/constraints/multihart_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_8h_multihart_ip_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bernard/book-2022.1/new_book_ip/multihart_ip/z1_multihart_8h_ip.srcs/sources_1/bd/design_1_8h/ip/design_1_8h_multihart_ip_0_1/design_1_8h_multihart_ip_0_1.xci
# IP: The module: 'design_1_8h_multihart_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bernard/book-2022.1/new_book_ip/multihart_ip/z1_multihart_8h_ip.gen/sources_1/bd/design_1_8h/ip/design_1_8h_multihart_ip_0_1/constraints/multihart_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_8h_multihart_ip_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
