# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/goossens/book-2022.1/new_book_ip/multicore_multihart_ip/z1_multicore_multihart_2c_2h_ip.srcs/sources_1/bd/design_1_2c_2h/ip/design_1_2c_2h_multihart_ip_0_27/design_1_2c_2h_multihart_ip_0_27.xci
# IP: The module: 'design_1_2c_2h_multihart_ip_0_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/goossens/book-2022.1/new_book_ip/multicore_multihart_ip/z1_multicore_multihart_2c_2h_ip.gen/sources_1/bd/design_1_2c_2h/ip/design_1_2c_2h_multihart_ip_0_27/constraints/multihart_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_2c_2h_multihart_ip_0_27'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/goossens/book-2022.1/new_book_ip/multicore_multihart_ip/z1_multicore_multihart_2c_2h_ip.srcs/sources_1/bd/design_1_2c_2h/ip/design_1_2c_2h_multihart_ip_0_27/design_1_2c_2h_multihart_ip_0_27.xci
# IP: The module: 'design_1_2c_2h_multihart_ip_0_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/goossens/book-2022.1/new_book_ip/multicore_multihart_ip/z1_multicore_multihart_2c_2h_ip.gen/sources_1/bd/design_1_2c_2h/ip/design_1_2c_2h_multihart_ip_0_27/constraints/multihart_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_2c_2h_multihart_ip_0_27'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
